### ISSUE TITLE
Support to UWP?

### ISSUE THREAD

**Issue by nicolgit** [xabre/xamarin-bluetooth-le#100]
Great plugin!

Any plan to support also **UWP**?

**Comment by smstuebe** [comment]
See #14 .

We planned it, but struggled a bit, because the UWP API has a different approach. So we focused on Android and iOS. But if we have some more time, we will definitely have a look :>

**Comment by CarbontTitan** [comment]
Have you had any further progress with support for UWP?
This works beautifully for iOS and Android but we need UWP support also.
