### ISSUE TITLE
Multiple notifications don't work

### ISSUE THREAD

**Issue by gaminn** [xabre/xamarin-bluetooth-le#103]
Device LG G3, Android API 23.

```
characteristics = new List<Plugin.BLE.Abstractions.Contracts.ICharacteristic>();
characteristics.Add(...); // characteristic 1
characteristics.Add(...); // characteristic 2
characteristics.Add(...); // characteristic 3
characteristics.Add(...); // characteristic 4
characteristics.Add(...); // characteristic 5
characteristics.Add(...); // characteristic 6

foreach (var characteristic in characteristics)
{
    characteristic.StartUpdates();
    characteristic.ValueUpdated += Characteristic_ValueUpdated;
}
```

First call of StartUpdates returns:

`Characteristic.StartUpdates, successful: True`

The rest of the calls return:

`Characteristic.StartUpdates, successful: False`

I found out that adding delay in the code:

```
foreach (var characteristic in characteristics)
{
    characteristic.StartUpdates();
    characteristic.ValueUpdated += Characteristic_ValueUpdated;
    await Task.Delay(150);
}
```

"fixes" the issue. The delay must be at least 150 ms.

**Comment by smstuebe** [comment]
Can you use the latest beta version and use `StartUpdatesAsync()`??

`await` characteristic.StartUpdatesAsync();`

**Comment by xabre** [comment]
@gaminn This should be fixed in the latest beta. We were not waiting for the descriptor write callback. This added a breaking change and ```StartUpdates()``` was replaced by ```StartUpdatesAsync()```

**Comment by gaminn** [comment]
Thanks guys! Beta fixes this.
