### ISSUE TITLE
Android - Device name always NULL (device discovered event)

### ISSUE THREAD

**Issue by PawelGasiorowski** [xabre/xamarin-bluetooth-le#113]
Hi,

I have a problem with the Device Name. It does not depand on device model. On all devices I have tested I get NULL device name on OnDiscovered event. On IOS there is no problem. Device names are fine. On always get NULL. Rest parameters are fine and I can connect to the device.

## Expected behavior
On both platforms OnDiscovered returns IDevice object that has name.

## Actual behavior
On IOS devices has name while on Android it is always NULL.

## Configuration

**Version:** 1.1.0

**Platform:** Android

**Comment by xabre** [comment]
Have you tried the sample App, does it happen with it?

**Comment by xabre** [comment]
Do you have any code you can share? The sample app seems to work fine. So does our current production app.

**Comment by xabre** [comment]
I'm guessing it's not an issue anymore
