### ISSUE TITLE
Connecting or disconnecting device from GetSystemConnectedOrPairedDevices() does nothing

### ISSUE THREAD

**Issue by Cheesebaron** [xabre/xamarin-bluetooth-le#122]
## Steps to reproduce

1. Connect to BLE device
2. Stop debugging in VS
3. Relaunch App
4. Try connecting or disconnect a device from `GetSystemConnectedOrPairedDevices()`

## Expected behavior
Should either connect or disconnect device

## Actual behavior
Nothing happens when trying to connect

When trying to disconnect the device a message like: `Disconnect async: device <device name> not in the list of connected devices.` is spat out.

## Configuration

**Version:** 0.9.3

**Platform:** Android 6.0.1

**Device:** Nexus 5X

**Comment by xabre** [comment]
Fixed in 1.2.0-beta4 :)
