### ISSUE TITLE
Samlpe App doesn't work

### ISSUE THREAD

**Issue by Maaarek** [xabre/xamarin-bluetooth-le#123]
Hi,

deployed your sample am on my phone but it doesn't start to detect any kind of devices .
Bluetooth is on.

**Comment by smstuebe** [comment]
That's a **bit** too little information. What do you want us to do with the information you provided?

**Comment by Maaarek** [comment]
It is now working very well.

**Comment by xabre** [comment]
You probably forgot to grant the location permissions (check logcat) ... or pull to refresh the list :P
