### ISSUE TITLE
Writing/reading >20 bytes

### ISSUE THREAD

**Issue by gaminn** [xabre/xamarin-bluetooth-le#128]
Hi,
is reading/writing >20 bytes from/to characteristic supported with this plugin? If so, please share how to do it?

**Comment by xabre** [comment]
@gaminn Not yet :) 

We have an implementation idea (but we need more info) but nothing in the plugin yet:
- On android: use the RequestMtu call/callback 
- On iOS: not sure? open question?

**Comment by Cheesebaron** [comment]
It seems to work fine for me? I just provide a byte array with the data and it eats it no problem. On Android I have had it eat around 450 bytes no problem.

**Comment by sarkreth** [comment]
@Cheesebaron Are you sure the byte array makes it to the peripheral as expected? Also, what device are you using?

**Comment by Cheesebaron** [comment]
Pretty sure it does. Have tried this on both iPhone and Android.

I can test again when I am back at work.

**Comment by martinwiboe** [comment]
Can confirm that it only works for me if I call `RequestMtu` with a sufficiently large value prior to writing. I'm using a OnePlus 3 with Nougat.

**Comment by xabre** [comment]
@martinwiboe Did you also try it on iOS?

**Comment by martinwiboe** [comment]
@xabre No, not using your library, unfortunately. We do have a native iOS app that uses BLE to talk to the same product, and that works correctly without any adjustment to MTU etc.

**Comment by martinwiboe** [comment]
@Cheesebaron have you had time to test this? :)

**Comment by Dragon160** [comment]
We did an airtrace and discovered that iOS automatically calls an Exchange MTU request after establishing the connection. 
Android does not show this behaviour. I think the "requestMTU(xxx)" call needs to be done by the application itself.

@xabre Any plans to adopt this? :-)
