### ISSUE TITLE
Add CBCentralInitOptions support

### ISSUE THREAD

**Issue by flyingxu** [xabre/xamarin-bluetooth-le#129]
On iOS, currently `CBCentralManager` is initialized by 

`_centralManager = new CBCentralManager(DispatchQueue.CurrentQueue);`

https://github.com/xabre/xamarin-bluetooth-le/blob/e20941a7b9aeecec8d6d865652c7f76eae4bcc5b/Source/Plugin.BLE.iOS/BleImplementation.cs#L22

There is no way to pass in `CBCentralInitOptions` parameters. by `CBCentralInitOptions`, [system should display a warning dialog to the user if Bluetooth is powered off ](https://developer.apple.com/reference/corebluetooth/cbcentralmanageroptionshowpoweralertkey), then the user can be redirected to iOS setting, which is convenient for the user.

**Comment by bwenninger** [comment]
Is there a plan to add the ability to pass in options to the CBCentralManager constructor?  I'm looking for a way to not have iOS alert the user that Bluetooth is not turned on and the CBCentralManagerOptionShowPowerAlertKey option would allow this but I can't currently pass that key in.

**Comment by xabre** [comment]
Both **RestoreIdentifier** and **ShowPowerAlert** are supported now
