### ISSUE TITLE
Non-printable peripheral name + connection error = crash

### ISSUE THREAD

**Issue by sarkreth** [xabre/xamarin-bluetooth-le#132]
## Steps to reproduce

1. Make a peripheral with a name that uses non-printable characters, e.g. 0x4D67436B154D1501010141375B7D705D3366681A155E157E7547

2. Program the peripheral to interrupt and drop its own connection procedure.

3. Attempt a connection on the Central.

## Expected behavior
I get this error message
![capture](https://cloud.githubusercontent.com/assets/18270934/21598064/29b595c2-d10a-11e6-8571-1d3f4e645637.PNG)

## Actual behavior
"Unhandled Exception:
System.FormatException: Input string was not in a correct format."
is thrown by `TraceImplementation?.Invoke(format, args);` in Trace.cs

## Configuration

**Version:** 1.1.0

**Platform:** Android 6.0

**Device:** Samsung Galaxy S7

**Comment by xabre** [comment]
Thanks for pointing it out. Currently the standard Trace implementation is Console.WriteLine. This implementation handles all the output messages from the plugin. You can override it with your own implementation like this:

Somewhere in your app init add: 
`
Plugin.BLE.Abstractions.Trace.TraceImplementation = // anything which is a Action<string, object[]> 
`

**Comment by smstuebe** [comment]
Will be fixed with the next release.
