### ISSUE TITLE
How to keep the ble device awake

### ISSUE THREAD

**Issue by pvhd** [xabre/xamarin-bluetooth-le#134]
Hello, I'm using your library to connect to a ble nutrition scale. Every 2 minutes, the scale turns off by itself. So I would like to ask if there is any way to keep the scale awake. Thanks a lot.

**Comment by smstuebe** [comment]
We don't know anything about the scale ^^
I think you have to read the spec of the scale or contact its vendor.
What you can try, is to read values continuously, **but this is only a guess**. And maybe it will drain the battery very fast. So this is off topic for us, sorry.

**Comment by pvhd** [comment]
Thanks for your reply.
