### ISSUE TITLE
Characteristics in Android 4 and 5

### ISSUE THREAD

**Issue by MarekMacner** [xabre/xamarin-bluetooth-le#141]
Have different behaviour with the same application:
on Android 4.4 phone HUAWEI 
GetCharacteristicsAsync() - returns  1 characteristic of RFDuino (real UUID)
an Android 5.1 Samsung
GetCharacteristicsAsync() - returns  1 characteristic but differ UUID then real coded inside RFDUINO
in addition, when used GetCharacteristicAsync(propper uuid) - existing characteristic - not found.
on IOS - IPhone 5s 10.02
GetCharacteristicsAsync() - returns  1 characteristis of RFDuino (real UUID)

How to solve is?

**Comment by xabre** [comment]
Seems like the Samsung is caching an old value. Can you restart the Bluetooth/phone?

If that still does not work, try an other BLE Scanner Apps like nRF Connect for Mobile to connect and discover characteristics? [https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp&hl=en]( https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp&hl=en)

Does this app also show the wrong one?
