### ISSUE TITLE
Get connected state of a ble device

### ISSUE THREAD

**Issue by leelatoo** [xabre/xamarin-bluetooth-le#142]
How to get the current state of a ble device from app using Plugin.BLE?

Our app wants to check the current connected state of a ble device to the app.?

**Comment by xabre** [comment]
What about State in IDevice?
```
/// <summary>
/// State of the device.
/// </summary>
DeviceState State { get; }
```

@leelatoo I assume this is related to connecting a device which is already connected in iOS, right?

**Comment by xabre** [comment]
@leelatoo Any news here?

**Comment by leelatoo** [comment]
@xabre , Yes, 'state' property helps:)
