### ISSUE TITLE
WriteAsync never returns when disconnected

### ISSUE THREAD

**Issue by leifzars** [xabre/xamarin-bluetooth-le#149]
## Steps to reproduce

1. Connect,
2. Disconnect
3. Write Characteristic

## Expected behavior
Exception

## Actual behavior
Never Returns

## Configuration

**Version of the Plugin:** 1.1.0 

**Platform:** iOS 10.2

**Device:** i Phone 7 ...

**Comment by smstuebe** [comment]
same reason as #147
