### ISSUE TITLE
Sample App 

### ISSUE THREAD

**Issue by xabre** [xabre/xamarin-bluetooth-le#15]
Was thinking of also including a SampleApp (like a BLE explorer) maybe using Xamarin Forms for both platforms. 

- [x] Move Sample from UWP branch to 1.0
- [x] Device List Page
- [x] Service List Page
- [x] Characteristic List Page
- [x] Characteristic detail Page

**Comment by smstuebe** [comment]
I added the sample app in the uwp branch. We can now extend it to a ble explorer.

**Comment by smstuebe** [comment]
UWP is on hold. let's focus on a neat 1.0 for iOS and Android

**Comment by smstuebe** [comment]
build is currently failing because of resource.designer.cs. Removing the resources it not possible ^^ i can't find something for bitrise
