### ISSUE TITLE
BLE characteristic update event fired twice

### ISSUE THREAD

**Issue by pvhd** [xabre/xamarin-bluetooth-le#155]
## Steps to reproduce

1. Connect to ble device, get specific service using GetServiceAsync(Guid.Parse("service id")), get specific characteristic using GetCharacteristicAsync(Guid.Parse("characteristic id")). Then check if characteristic can update and assign ValueUpdated event

2. Put a break point inside the ValueUpdated event and found out the event is fired twice.

## Expected behavior
The ValueUpdated event should be fired once

## Actual behavior
The ValueUpdated event is fired twice

## Configuration

**Version of the Plugin:** 1.1.0 

**Platform:** Android 4.4.2

**Device:** LG G3

**Comment by xabre** [comment]
Please reopen if still an issue.

**Comment by LinuxAndOracle** [comment]
@pvhd How did you fired twice? I can't even get in once
