### ISSUE TITLE
UWP COMPATIBILITY UPDATE

### ISSUE THREAD

**Issue by yiyoMX** [xabre/xamarin-bluetooth-le#158]
Hi, I just wanted you to know that in the Windows 10 insider compilations the BLE api changed, its still faulty but they are trying to have the same capabilities as Android/IOS.
[More Info here](https://blogs.windows.com/buildingapps/2017/01/13/new-bluetooth-features-in-creators-update-gatt-server-bluetooth-le/#KwH761CvXIawdFMZ.97)
Best regards.

**Comment by xabre** [comment]
uwp prerelease v2.2.0-pre1
