### ISSUE TITLE
Error Implemented on CrossBluetoothLE.Current

### ISSUE THREAD

**Issue by CJACQUEL** [xabre/xamarin-bluetooth-le#166]
Hello, 
On the first instruction : 
var ble = CrossBluetoothLE.Current;
I have the message error :
System.NotImplementedException: This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.
Thank you,
Christophe

**Comment by CJACQUEL** [comment]
Its solve. I upgrade all the Nugets.

**Comment by jvhgamer** [comment]
This issue is occurring on version 1.3.0 and 2.0.0-pre1
