### ISSUE TITLE
Pb when current cut

### ISSUE THREAD

**Issue by CJACQUEL** [xabre/xamarin-bluetooth-le#170]
Hello, 
The library is working fine. 
But when there is a current cut of the device with the bluetooth, its not working anymore. Did there is a solution to reconnect to the bluetooth in such a case ? 
Thank you,
Christophe

**Comment by smsissuechecker** [comment]
Hi @CJACQUEL,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by smsissuechecker** [comment]
Hi @CJACQUEL,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by xabre** [comment]
Maybe this issue can help you:
#99
