### ISSUE TITLE
Just a test

### ISSUE THREAD

**Issue by smstuebe** [xabre/xamarin-bluetooth-le#171]
Test issue

**Comment by smsissuechecker** [comment]
Hi @smstuebe,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by smsissuechecker** [comment]
Hi @smstuebe,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!
