### ISSUE TITLE
ValueUpdated event not fired on Android for a notify characteristic 

### ISSUE THREAD

**Issue by shayo** [xabre/xamarin-bluetooth-le#177]
I am running an app on Xamarin Forms and using your plugin to communicate with a Nordic NRF51 module. Overall, everything works fine. I can send commands and get notifications on both iOS and Android.
The problem started when I tried to run code that runs device firmware update (FOTA).
This procedure requires to send some commands to a control characteristic, and then wait for a reply notification over another. 
The shared code I'm using works without a problem on iOS devices, but fails on Android devices because I never get that notification.
This is peculiar because for all other characteristics, I do get notifications back from the Android device.

I'm using version 1.2.1.
Android is Moto G, running v5.1 

I know this isn't much to work on (specially because it only doesn't work on this very specific instance), but what could possibly cause this?
Is there some hint / lead I can follow in your code to assess why notifications are not received for this characteristic? (again - everything works fine in iOS, and everything works fine for other characteristics in Android).

**Comment by smsissuechecker** [comment]
Hi @shayo,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by cipriancoj** [comment]
I had the same problem with an old version of these apis but with the last one I solved it!

**Comment by xabre** [comment]
Which version are you using now? 1.2.3 or 1.3.0-alpha ?

**Comment by cipriancoj** [comment]
Now I'm using the 1.2.3
