### ISSUE TITLE
The sample app doesnt work

### ISSUE THREAD

**Issue by Hussamalsh** [xabre/xamarin-bluetooth-le#179]
Hi

When i run the example app on my android device  (Samsung galaxy s7) i got the following error:

Unhandled Exception:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.

on line 33 in MainActivity.cs    ( Mvx.Resolve<IMvxAppStart>().Start();)

## Configuration

**Platform:** / Android 

**Device:** / Samsung galaxy s7

Best regards Hussam

**Comment by smsissuechecker** [comment]
Hi @Hussamalsh,

I'm the friendly issue checker.
It seems like (62.50 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by xabre** [comment]
@Hussamalsh I've just checked out and deployed the current state of the sample app form the master branch. Seems to be running fine. 

Please check your Android SDK Manager, maybe something is missing there or out of date. Do a clean build after you install the needed stuff. Moreover, please try to include a more detailed stack trace.

**Comment by xabre** [comment]
Closing issue
