### ISSUE TITLE
NuGet package for non mvx plugin

### ISSUE THREAD

**Issue by smstuebe** [xabre/xamarin-bluetooth-le#18]
- [x] add nuspec 
- [x] adjust existing nuspec based on [this blog post from james m](https://blog.xamarin.com/creating-reusable-plugins-for-xamarin-forms/)
- [ ] use shared Assembly infos (like: https://github.com/jamesmontemagno/Xamarin.Plugins/tree/master/Permissions)
- [x] update the nuget pack script
- [x] test the nuget package locally before upload [Infos here](https://blog.xamarin.com/creating-reusable-plugins-for-xamarin-forms/)
- [x] create upload script
- [x] create package on nuget
- [x] add to build process
- [x] update icon (update it on the mvx nuspec, too)

**Comment by xabre** [comment]
Added some additional point to the list.

**Comment by smstuebe** [comment]
damn... where can I see the diff? :D

**Comment by xabre** [comment]
- [ ] adjust existing nuspec (include pdb, xml)
- [ ] update the nuget pack script
- [ ] test the nuget package locally before upload
- [ ] create upload script

Personal ToDo:
- [ ] invite contributors to CI

**Comment by xabre** [comment]
@smstuebe is this open point still relevant 'use shared Assembly infos' ?

**Comment by xabre** [comment]
@smstuebe Create issue for 

- [ ]  use shared Assembly infos (like: https://github.com/jamesmontemagno/Xamarin.Plugins/tree/master/Permissions)
