### ISSUE TITLE
UpdateRssiAsync() skip code

### ISSUE THREAD

**Issue by SeanStayn** [xabre/xamarin-bluetooth-le#183]
## Steps to reproduce

```
var rssiUpdateResult = await device.UpdateRssiAsync();
if (rssiUpdateResult)
{
      this.RssiUpdateEvent?.Invoke(this, new RssiUpdateEventArgs(device));
}
Debug.WriteLine("RSSI - UpdateMethodCallFinished : " + rssiUpdateResult;

```
## Expected behavior
I update the RSSI value from my device with the method device.UpdateRssiAsync(). With an if-condition I fire an event, if the method return true. After the if-condition, I send a message to the console.

## Actual behavior
Every line of code, after the method don't execute. I set breakpoints and the programm stops at the line of the UpdateRssiAsync method call, but it doesn't stop at the if-condition or the WriteLine method. Additionally I can't find any output from the WriteLine method.

In the console output, I can see the rssi value from the mvx:Diagnostic.

## Configuration

**Version of the Plugin:** v4.0.30319

**Platform:** PCL / Android 6.0 

**Device:** Samsung SM-A500FU

**Comment by smsissuechecker** [comment]
Hi @SeanStayn,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by tomridl** [comment]
Same issue on Samsung J5 (Android 5.1.1), plugin version 1.2.2. 

When I tested on a Pixel (Android 7.1.2), the code completed, but the RSSI value was never updated (remained the same as when the unit first connected, so moving the phone away from the unit did not cause a change in RSSI value). On iOS, the RSSI value dynamically updates when moving the phone closer or nearer the device.

**Comment by BradleyAlcock** [comment]
xamarin-bluetooth-le/Source/Plugin.BLE.Android/Device.cs

Line 206 if (args.Device.Id == Id) return;
this will always return based on my understanding of the code.

suggest enclosing the the other if/else within like this:

if (args.Device.Id == Id)
				  {

					  if (args.Error == null)
					  {
						  Trace.Message("Read RSSI for {0} {1}: {2}", Id, Name, args.Rssi);
						  Rssi = args.Rssi;
						  complete(true);
					  }
					  else
					  {
						  Trace.Message($"Failed to read RSSI for device {Id}-{Name}. {args.Error.Message}");
						  complete(false);
					  }
				  }

**Comment by tomridl** [comment]
Or:

` if (args.Device.Id != Id) return;`

**Comment by BradleyAlcock** [comment]
yep, that does work better, the return is used to stop returning the same rssi value again.

**Comment by xabre** [comment]
yes, you are right, problem got fixed in 1.3.0-alpha. 
I will also include it in a 1.2.3 release until we confirm that 1.3.0 is stable.

**Comment by xabre** [comment]
Fixed with v1.2.3 :)

**Comment by helderdb** [comment]
It's happening in 2.1.1 as well..

**Comment by daniel-streetec** [comment]
Hi, I can confirm that using 2.1.2 and Samsung Galaxy S10 the function will never return and any code execution is blocked.

`if (this.BLEDevice.State == Plugin.BLE.Abstractions.DeviceState.Connected)
            {
                await this.BLEDevice.UpdateRssiAsync();
                return this.BLEDevice?.Rssi ?? -1;
            } else
            {
                return -1;
            }`
