### ISSUE TITLE
ScanSettings

### ISSUE THREAD

**Issue by Cheesebaron** [xabre/xamarin-bluetooth-le#184]
Scanning on Android is sloooooooow. Especially if you have more than 10 BLE devices nearby. 

https://github.com/xabre/xamarin-bluetooth-le/blob/master/Source/Plugin.BLE.Android/Adapter.cs#L124

I see currently you just use the default ScanSettings, which defaults to LOW_POWER scanning.

Please let choose the mode to scan with.

**Comment by smsissuechecker** [comment]
Hi @Cheesebaron,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by smstuebe** [comment]
Duplicate of #136
