### ISSUE TITLE
after update to 1.2.2 . start then Exception

### ISSUE THREAD

**Issue by chenjeff622** [xabre/xamarin-bluetooth-le#186]
after upgrade to 1.12.2 . same code run and Exception error.  does it change some code?
RAD : visual studio 2017 4.7.02046
Plugin.BLE : 1.2.2
Mobile : API23 (Android 6.0)

OUTPUT:
04-06 16:51:17.398 I/MonoDroid( 6138): UNHANDLED EXCEPTION:
04-06 16:51:17.447 I/MonoDroid( 6138): System.MissingMethodException: Method 'Android.Bluetooth.BluetoothAdapter.StartLeScan' not found.
04-06 16:51:17.447 I/MonoDroid( 6138):   at Plugin.BLE.Abstractions.AdapterBase+<StartScanningForDevicesAsync>d__37.MoveNext () [0x000d1] in C:\Users\Adrian\Documents\GitHub\xamarin-bluetooth-le\Source\Plugin.BLE.Abstractions\AdapterBase.cs:61 
04-06 16:51:17.447 I/MonoDroid( 6138): --- End of stack trace from previous location where exception was thrown ---
04-06 16:51:17.447 I/MonoDroid( 6138):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <e26f1ee453814c0ba7d5dc5561b982b8>:0 
04-06 16:51:17.448 I/MonoDroid( 6138):   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <e26f1ee453814c0ba7d5dc5561b982b8>:0 
04-06 16:51:17.448 I/MonoDroid( 6138):   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <e26f1ee453814c0ba7d5dc5561b982b8>:0 
04-06 16:51:17.448 I/MonoDroid( 6138):   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <e26f1ee453814c0ba7d5dc5561b982b8>:0 
04-06 16:51:17.448 I/MonoDroid( 6138):   at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <e26f1ee453814c0ba7d5dc5561b982b8>:0 
04-06 16:51:17.448 I/MonoDroid( 6138):   at App2.Page1Tab1+<ScanBTLE>d__2.MoveNext () [0x00229] in D:\PROJECT\VS2017\Projects\App2\App2\App2\Page1Tab1.xaml.cs:45 
04-06 16:51:17.448 I/MonoDroid( 6138): --- End of stack trace from previous location where exception was thrown ---
04-06 16:51:17.448 I/MonoDroid( 6138):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <e26f1ee453814c0ba7d5dc5561b982b8>:0 
04-06 16:51:17.448 I/MonoDroid( 6138):   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>m__0 (System.Object state) [0x00000] in <e26f1ee453814c0ba7d5dc5561b982b8>:0 
04-06 16:51:17.448 I/MonoDroid( 6138):   at Android.App.SyncContext+<Post>c__AnonStorey0.<>m__0 () [0x00000] in <199c50f0faff4e01ac5b1e26da8b11bd>:0 
04-06 16:51:17.448 I/MonoDroid( 6138):   at Java.Lang.Thread+RunnableImplementor.Run () [0x0000b] in <199c50f0faff4e01ac5b1e26da8b11bd>:0 
04-06 16:51:17.448 I/MonoDroid( 6138):   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <199c50f0faff4e01ac5b1e26da8b11bd>:0 
04-06 16:51:17.448 I/MonoDroid( 6138):   at (wrapper dynamic-method) System.Object:69a14ca1-5491-4fca-ab78-4177bc01bade (intptr,intptr)
04-06 16:51:17.469 W/art     ( 6138): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
04-06 16:51:17.475 D/Mono    ( 6138): DllImport searching in: '__Internal' ('(null)').
04-06 16:51:17.475 D/Mono    ( 6138): Searching for 'java_interop_jnienv_throw'.
04-06 16:51:17.475 D/Mono    ( 6138): Probing 'java_interop_jnienv_throw'.
04-06 16:51:17.475 D/Mono    ( 6138): Found as 'java_interop_jnienv_throw'.

**Comment by smsissuechecker** [comment]
Hi @chenjeff622,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by chenjeff622** [comment]
sorry . i  will close the issue.
