### ISSUE TITLE
Working with a WPF application

### ISSUE THREAD

**Issue by CJACQUEL** [xabre/xamarin-bluetooth-le#193]
Hello, 
Does this library is working for a WPF application ? 
Thx
Christophe

**Comment by smsissuechecker** [comment]
Hi @CJACQUEL,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by smstuebe** [comment]
See: https://github.com/xabre/xamarin-bluetooth-le#support--limitations
