### ISSUE TITLE
Data corrupted

### ISSUE THREAD

**Issue by CJACQUEL** [xabre/xamarin-bluetooth-le#197]
Hello, 
I received messages of 16 bytes long by bluetooth. 
But some times the message is corrupted. 
How to process it ?
Thank you,
Christophe

**Comment by smsissuechecker** [comment]
Hi @CJACQUEL,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by sarkreth** [comment]
The BLE Link Layer guarantees delivery of intact packets, so your issue is probably happening at the application level. How is the data getting "corrupted"? Is it being overwritten with previous data? Is it being truncated? Do you notice any pattern in the corruptions?

**Comment by xabre** [comment]
Close due to inactivity
