### ISSUE TITLE
Cached services and characteristics not cleared on signal loss

### ISSUE THREAD

**Issue by xabre** [xabre/xamarin-bluetooth-le#198]
On Android, cached services are not cleared on signal loss.
Services are cleared only when the user triggers the device disconenct and not when disconnection is caused by something else.

## Steps to reproduce

1. Connect to device.

2. Trigger a signal loss.

3. Get back in range.

4. Reconnect using same IDevice instance. 

5. Service/ Characteristic operations will fail because they work on stale cached instances. For example Characteristic write / read.

## Expected behavior
Clear cached services/characteristic on any type of connection loss.

## Actual behavior
Cached Services/Characteristics etc not cleared

### Crashlog

Not applicable

## Configuration

**Version of the Plugin:** 
1.3.0-beta1

**Platform:** 
Android All

**Device:** 
All android devices.

**Comment by smsissuechecker** [comment]
Hi @xabre,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by xabre** [comment]
Fixed with 1.3.0-beta2
