### ISSUE TITLE
Question: bluetooth device identifier

### ISSUE THREAD

**Issue by shayo** [xabre/xamarin-bluetooth-le#201]
This is more of a question that a bug report.
I am wondering why do I get different device identifiers with Android and iOS for the same physical device? Also, I encountered that two different iOS phones give difference device identifiers to the same physical device.
Is this normal?

**Comment by smsissuechecker** [comment]
Hi @shayo,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by xabre** [comment]
Each iOS device assigns a GUID to a known BLE peripheral which has nothing to do with the it's mac  address (unfortunately). This means that the same Peripherial will have different 'id' s on all iPhones. This is a limitation of the apple implementation as far as I know. If you can find a way to get the hw address of a CB Peripherial please share it:)

Also see #194 for more info.
