### ISSUE TITLE
Is it necessary to wait for CharacteristicValueWritten when WriteType is WithoutResponse on Android?

### ISSUE THREAD

**Issue by flyingxu** [xabre/xamarin-bluetooth-le#202]
## Steps to reproduce

1. Find a bluetooth device which support WriteWithoutResponse

2. Run the BleClient application on Android and iOS

Set the Write type to WithoutResponse 

3. See the Mvx diagnosis
[0:] mvx:Diagnostic:**341.07** Characteristic.WriteAsync
[0:] mvx:Diagnostic:**341.09** Write (some guid)
[0:] mvx:Diagnostic:**341.11** OnCharacteristicWrite: value 00-78-00-00-00-00-00-00-21-E6 status Success

See how much time a `WriteAsync()` cost
## Expected behavior
When WriteType is WithoutReponse, it's expected to be much faster than WithResponse, 

## Actual behavior
Here more then 20 ms is spend in a `WriteAsync()`. There is no difference between WithResponse from WithoutResponse, which make it way slow than iOS in WithoutReponse type.

### Reference code
I see Android always wait for the event no matter it's WithResponse  or WithoutResponse, but iOS just wait for event when WithResponse  .

#### Android 

        protected override async Task<bool> WriteNativeAsync(byte[] data, CharacteristicWriteType writeType)
        {
            _nativeCharacteristic.WriteType = writeType.ToNative();

            return await TaskBuilder.FromEvent<bool, EventHandler<CharacteristicWriteCallbackEventArgs>>(
                execute: () => InternalWrite(data),
                getCompleteHandler: (complete, reject) => ((sender, args) =>
                   {
                       if (args.Characteristic.Uuid == _nativeCharacteristic.Uuid)
                       {
                           complete(args.Exception == null);
                       }
                   }),
               subscribeComplete: handler => _gattCallback.CharacteristicValueWritten += handler,
               unsubscribeComplete: handler => _gattCallback.CharacteristicValueWritten -= handler
            );
        }

#### iOS
        protected override Task<bool> WriteNativeAsync(byte[] data, CharacteristicWriteType writeType)
        {
            Task<bool> task;

            var nativeWriteType = writeType.ToNative();
            if (nativeWriteType == CBCharacteristicWriteType.WithResponse)
            {
                task = TaskBuilder.FromEvent<bool, EventHandler<CBCharacteristicEventArgs>>(
                    execute: () => { },
                    getCompleteHandler: (complete, reject) => (sender, args) =>
                    {
                        if (args.Characteristic.UUID != _nativeCharacteristic.UUID)
                            return;

                        complete(args.Error == null);
                    },
                    subscribeComplete: handler => _parentDevice.WroteCharacteristicValue += handler,
                    unsubscribeComplete: handler => _parentDevice.WroteCharacteristicValue -= handler);
            }
            else
            {
                task = Task.FromResult(true);
            }

            var nsdata = NSData.FromArray(data);
            _parentDevice.WriteValue(nsdata, _nativeCharacteristic, nativeWriteType);

            return task;
        }

I'm not sure if it's the desired Android design.

## Configuration

**Version of the Plugin:** e.g. 1.2.1

**Platform:**  iOS 10.3 / Android 7 

**Device:** Galaxy S7 /i Phone 6

**Comment by smsissuechecker** [comment]
Hi @flyingxu,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by flyingxu** [comment]
Sorry, I made a mistake as to the data. There is a difference in the write time between WithReponse and WithoutResponse in Android. 
So maybe in Android, it's necessary to wait for the event always.
