### ISSUE TITLE
Problem of speed reading

### ISSUE THREAD

**Issue by CJACQUEL** [xabre/xamarin-bluetooth-le#203]
Hello, 
size = 32
When I do  await sock.InputStream.ReadAsync(buffer2, 0, size);
I receive the data but not in real time, there is a delay, as if the buffer was long to get empty. 
Maybe the emitter send too much of data ? 
Could you help ? 
Thank you,
Christophe

**Comment by smsissuechecker** [comment]
Hi @CJACQUEL,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!
