### ISSUE TITLE
Question: Connection Parameter

### ISSUE THREAD

**Issue by simson51** [xabre/xamarin-bluetooth-le#206]
Hi, 
in order to improve performance we would like to adjust the connection parameters.
https://developer.android.com/reference/android/bluetooth/BluetoothGatt.html#CONNECTION_PRIORITY_HIGH
Could you give me some advise on how to achieve this?

## Expected behavior
set connection parameter to high

**Comment by smsissuechecker** [comment]
Hi @simson51,

I'm the friendly issue checker.
It seems like (87.50 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by Dragon160** [comment]
Hi @simson51 ,

updating the connection interval is included in the latest beta version of the plugin. Please be aware that this is only possible for android.

You can use it like this:
`_myConnectedDevice.UpdateConnectionInterval(ConnectionInterval.High);`
