### ISSUE TITLE
Support for multiple simultaneous devices.

### ISSUE THREAD

**Issue by SeppyMoose** [xabre/xamarin-bluetooth-le#221]
It appears that whenever i connect to a second BLE device the first one stops updating characteristics. Is this expected behavior or should it support multiple simultaneous devices?

The code I'm using to connect is:
                        mAdapter.StopScanningForDevicesAsync().Wait();
                        mAdapter.ConnectToDeviceAsync(input.mDevice).Wait();

I've tried lots of things, including manually reconnecting to all "connected_devices".

**Comment by smsissuechecker** [comment]
Hi @SeppyMoose,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!
