### ISSUE TITLE
Sample app

### ISSUE THREAD

**Issue by nodoid** [xabre/xamarin-bluetooth-le#230]
The docs for this project refers to a sample project, but I can't find a link to it. Is there one?

**Comment by smsissuechecker** [comment]
Hi @nodoid,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by xabre** [comment]
The sample app csproj are in /Source/BLE.Client/. If you open the BLE.sln they are under the Sample solution folder. You have to checkout and build the sample for yourself.
