### ISSUE TITLE
What is DeviceState.Limited ?

### ISSUE THREAD

**Issue by AnoopChatra** [xabre/xamarin-bluetooth-le#231]
Hi,

What is DeviceState.Limited ??

I am using the following method to connect to a BLE device with isAutoConnect set to true in an android application :
_adapter.ConnectToDeviceAsync(device, new ConnectParameters(isAutoConnect),
                                reconnectCancelToken.Token);

After successful connection the device state will be DeviceState.Connected  but however after the reconnection the device state of the remote BLE device would be  "DeviceState.Limited" . 
Could you please explain what state it is ?? I could not find any co related state in the native android. 

PluginVersion : 1.3.0 beta 3
Android Device : Google Pixel (Android 7.1.1)

Regards,
Anoop Chatra

**Comment by smsissuechecker** [comment]
Hi @AnoopChatra,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!
