### ISSUE TITLE
Switch to netstandard

### ISSUE THREAD

**Issue by smstuebe** [xabre/xamarin-bluetooth-le#237]
Switch to netstandard

- [x] convert pcls to netstandard
- [x] make bitrise working 
- [x] make version update working (no AssemblyInfo.cs anymore)
- [x] Test install

**Comment by smsissuechecker** [comment]
Hi @smstuebe,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!
