### ISSUE TITLE
UWP Support 

### ISSUE THREAD

**Issue by JanNepras** [xabre/xamarin-bluetooth-le#249]
Are you going to support UWP version? I tried the uwp_creators_update branch and it doesn't work properly. I would like to help with contribution. Could someone tell me what needs to be done?

**Comment by smsissuechecker** [comment]
Hi @JanNepras,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by flyingxu** [comment]
What specifically is not working? Please check the issue template and follow it to provide some more information.
