### ISSUE TITLE
iOS implementation of IAdapter does not invoke DeviceDisconnected on bluetooth turn off

### ISSUE THREAD

**Issue by d768** [xabre/xamarin-bluetooth-le#264]
iOS adapter does not invoke DeviceDisconnected event on bluetooth turn off.
Already created fix #263 

## Steps to reproduce

1. Connect to BLE device

2. Turn bluetooth off

3. IAdapter.DeviceDisconnected is not invoked

## Expected behavior
iOS adapter should invoke DeviceDisconnected for each device in _deviceConnectionRegistry.

## Actual behavior
CBCentralManager.UpdateState to CBCentralManagerState.PoweredOff is ignored and IAdapter.DeviceDisconnected is not invoked.

## Crashlog
None

## Configuration

**Version of the Plugin:** 1.3.0

**Platform:** iOS 11.1

**Device:** e.g. iPhone 7

**Comment by smsissuechecker** [comment]
Hi @d768,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by lamest** [comment]
same issue on iOS 11. looks like iOS 9 works fine.

**Comment by xabre** [comment]
Merged the PR. Will add it to the next release
