### ISSUE TITLE
Removed the delay(100) without any problems, resulted in speedup :)

### ISSUE THREAD

**Issue by Tijgerd** [xabre/xamarin-bluetooth-le#266]
I removed the delay from Characteristic.cs in line 127 and it fixed the delay between messages.
Or I fixed by editing something else.. can't remember..
But it sure didn't hurt the performance of my android application so that's a :+1: 

https://github.com/xabre/xamarin-bluetooth-le/blob/b30950113e40defcf1d612fdc972708be2137a16/Source/Plugin.BLE.Android/Characteristic.cs#L127

**Comment by smsissuechecker** [comment]
Hi @Tijgerd,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by xabre** [comment]
- [ ]

**Comment by Tijgerd** [comment]
I do need to note that I added a small delay after this function finished executing.
It seems the device needs to notice the notification request but I found that the delay after the execution of this function can be shorter (10ms)

**Comment by xabre** [comment]
released with 2.1.0
