### ISSUE TITLE
Incompatible using Code Sharing .NETStandard

### ISSUE THREAD

**Issue by JTrotta** [xabre/xamarin-bluetooth-le#267]
This plugin does not work with the new XPlatform Code sharing strategy template .NETStandard. 
The App can be compiled, but when this instruction is held, the App crashes:
`var _ble = CrossBluetoothLE.Current;`

Also in VS, got this warning:
![image](https://user-images.githubusercontent.com/2145654/33797913-3c072b88-dd10-11e7-813a-8903c28684ed.png)

# Steps to reproduce

1. Create a new blank application with the new template using code sharing template  .NETStandard

2. Add the plugin

3. Initialize Vanilla style

## Expected behavior
Working

## Actual behavior
Crash, calling `var _ble = CrossBluetoothLE.Current;`

### Crashlog

Unhandled Exception:
Java.Lang.ClassNotFoundException: <Timeout exceeded getting exception details> occurred

## Configuration

**Version of the Plugin:** e.g. 1.0.0 / 1.0.1-alpha3
1.3.0
**Platform:** e.g. iOS 10.1 / Android 4.4 / ... (including version!!! e.g. Android 5.1 / i0S 10)
Android 7.0
**Device:** e.g. HTC Sensation /i Phone 7 ...
Asus Zenphone 3 during debuging

**Comment by smsissuechecker** [comment]
Hi @JTrotta,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by jpflueger** [comment]
@JTrotta I'm able to use this library on both platforms without exception. Did you put this in your csproj file? 
```	
<PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssertTargetFallback>$(AssertTargetFallback);portable45-net45+win8+wpa81</AssertTargetFallback>
</PropertyGroup>
```

**Comment by JTrotta** [comment]
Hello. Yes I added it to the common project. But as soon as this instruction is called `CrossBluetoothLE.Current;` I got the java error "Java.Lang.ClassNotFoundException: occurred".
I'm using the very last version of VS17 15.5.1 and Android 4.8.0.753

**Comment by dugasz1** [comment]
Same problem here with VS17 15.5.1 and Xamarin 4.8.0.753.

**Comment by tribe84** [comment]
Same issue here.

**Comment by biapar** [comment]
Solved?

**Comment by xabre** [comment]
Starting with version 2.0.0 we target .net standard
