### ISSUE TITLE
How to get the ScanResponse?

### ISSUE THREAD

**Issue by erdmenchen** [xabre/xamarin-bluetooth-le#269]
Maybe I am missing it in the documentation, but how can we get the scan response during 
`Adapter.StartScanningForDevicesAsync`?

In the device object that is reported in the `Adapter.DeviceAdvertised` Event  there does not seem to be any scan response related field...

**Comment by smsissuechecker** [comment]
Hi @erdmenchen,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by xabre** [comment]
Check the 'AdvertisementRecords' proeprty of a device instance returned by the scan events.

From IDevice:
```
        /// <summary>
        /// All the advertisment records
        /// For example:
        /// - Advertised Service UUIDS
        /// - Manufacturer Specifc data
        /// - ...
        /// </summary>
        IList<AdvertisementRecord> AdvertisementRecords { get; }
```

**Comment by erdmenchen** [comment]
So it looks like the `ScanResponse` field is automatically appended to the advertisement records by the currently used platform mechanics. Since the scan response carries its own data fields, they are found in the advertisement records each by its self, they are not bundled up as `ScanResponse` somehow.

I also misunderstanded/didn´t know that iOS / Android is already requesting the ScanResponse by its self and that it is appended to the advertisement records. I thought I have to somehow request it manually. 

Thanks!
