### ISSUE TITLE
Create package install test projects

### ISSUE THREAD

**Issue by smstuebe** [xabre/xamarin-bluetooth-le#27]
Create 2 solutions that contain

- [x] Empty App (Core, iOS, Android)
- [x] Empty MvvmCross App (Core, iOS, Android)
- [x] Add references to Adapter (similar to linker please include) "compiler please check"

Script that 

- [x] installs the nuget packages from local source
- [ ] updates the packages to the latest version
- [x] builds the apps 

to ensure that packages are installable and cause no build error.

**Comment by xabre** [comment]
F# target: "sanity-check" 

- builds the project
- nuget pack 
- restores/updates packages for dummy project and builds
