### ISSUE TITLE
IGattCharacteristic.Read() does not timeout/error on iOS

### ISSUE THREAD

**Issue by fmarkov** [xabre/xamarin-bluetooth-le#272]
On iOS the Read method never times out or errors out like on Android.

## Steps to reproduce

1. Have a valid BLE device and a readable characteristic.

2. With the device on, do a read.  It will be successful.

3. Turn off the device immediately before the Read() method is called.  On Android in ~20 seconds an Exception will be thrown (good).  On iOS it jus sits there indefinitely.

## Expected behavior
Like Android, please timeout and throw an exception.

## Actual behavior
On IOS it just sits there.

### Crashlog

N/A

## Configuration

**Version of the Plugin:** 3.1.1

**Platform:** e.g. iOS 11.0.3

**Device:** e.g. i Phone 6

**Comment by smsissuechecker** [comment]
Hi @fmarkov,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by xabre** [comment]
should be fixed in 2.0.0-pre1
