### ISSUE TITLE
Question: how to cancel a connection request 

### ISSUE THREAD

**Issue by shayo** [xabre/xamarin-bluetooth-le#275]
ConnectToKnownDeviceAsync(...)

Q: How can I cancel the connect request while it is still takes place?

**Comment by smsissuechecker** [comment]
Hi @shayo,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by erdmenchen** [comment]
Just use the `CancellationToken`, see https://github.com/xabre/xamarin-bluetooth-le/blob/18d04c5c5134b27e97dbdd19f1a4a94aeb122ed3/Source/Plugin.BLE.Abstractions/Contracts/IAdapter.cs#L114

**Comment by shayo** [comment]
I thought CancellationToken is only to monitor the cancel operation. How do I initiate the cancel operation ?can you please post a small code snippet?
I didn’t find any Cancel method in the cancellationToken object.

**Comment by erdmenchen** [comment]
You have to use a [CancellationTokenSource](https://msdn.microsoft.com/en-us/library/system.threading.cancellationtokensource).
There you have the `Token`-Property for the `ConnectToKnownDeviceAsync` call and also the [Cancel-Method](https://msdn.microsoft.com/en-us/library/dd321955) to indicate the cancellation.


e.g. (pseudo code):
```
var token = new CancellationTokenSource();
await adapter.ConnectToKnownDeviceAsync(new Guid(), token.Token);
token.Cancel();
```

**Comment by shayo** [comment]
Gotcha. Thank you!

**Comment by erdmenchen** [comment]
I must confess, that I am experiencing issues with this approach on Android:

Triggering a connect and then cancelling it, does not stop the underlying connection process. 
Because later some time after cancellation via the cancellation token, suddenly the connection is established...
