### ISSUE TITLE
StartScanningForDevicesAsync throw Exception

### ISSUE THREAD

**Issue by KhangYu** [xabre/xamarin-bluetooth-le#278]
Hi, guys,
I got an exception when try to scan BLE devices. The message showed "Field overflow on store 'InterpretedSystem.Runtime.ComplierServices.lAsyncStateMachineVT.<>U__1".
Does anyone have this issue before? Thanks :)

`IAdapter adapter = CrossBluetoothLE.Current.Adapter;
adapter.DeviceDiscovered += (s, a) =>  { };
adapter.StartScanningForDevicesAsync();`

## Configuration

**Version of the Plugin:** 1.3.0

**Platform:** iOS 10.1

**Device:** iPhone 7+

**Comment by smsissuechecker** [comment]
Hi @KhangYu,

I'm the friendly issue checker.
It seems like (50.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by lamest** [comment]
could it be recursion in your code that call async methods repeatedly?

**Comment by KhangYu** [comment]
Actually i run my sample app on xamarin live player, could it be the cause of this issue?

**Comment by xabre** [comment]
Try the sample app :)
