### ISSUE TITLE
Continuous connection question

### ISSUE THREAD

**Issue by freerk92** [xabre/xamarin-bluetooth-le#279]
I had the same question as Shayo, but his thread is ignored because it isn't according to the template. 

Original question:
> This is a question, not a real issue.
> What are the rules regarding ConnectToKnownDeviceAsync ?
> When does it fail / time out?
> How do I use the cancellation token to indicate to stop this operation?
> 
> I basically want to have a thread that continuously searches for a known device and tries to maintain connectivity with it. What's the best way to achieve this?
> (i.e., try to connect, if fail after some predefined amount of time, try again).

The rest of the template is from my own project.

## Steps to reproduce

1. No steps, it's just a question

2. See step 1

3. See step 2

## Expected behavior Tell us what should happen:
I want to connect to a device, when connected I expect to also see it in the settings as connected.

## Actual behavior Tell us what happens instead:
It seems my device isn't really connected to my phone. When I check the bluetooth in settings there is no connection

### Crashlog
No crash

## Configuration

**Version of the Plugin:** e.g. 1.3.0

**Platform:** Xamarin.Forms Android 7.0

**Device:** e.g. Samsung Galaxy S6 Edge

**Comment by smsissuechecker** [comment]
Hi @freerk92,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by xabre** [comment]
#273
