### ISSUE TITLE
Connection on Android hangs if bluetooth is off

### ISSUE THREAD

**Issue by lamest** [xabre/xamarin-bluetooth-le#282]
## Steps to reproduce

1. Turn bluetooth device of your phone off

2. Call `var t=ConnectToKnownDeviceAsync(id)`

## Expected behavior
connection fail or timed out

## Actual behavior
Device never connects and task t is never completes, even when bluetooth is on again.

## Configuration

Android 5.1.1 on samsung j1

what i found is in device.cs 
`BluetoothDevice.ConnectGatt(Application.Context, connectParameters.AutoConnect, _gattCallback);`
returns null when bluetooth is off and not null if on. so i use this now to throw an exception.

**Comment by smsissuechecker** [comment]
Hi @lamest,

I'm the friendly issue checker.
It seems like (50.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by xabre** [comment]
Duplicate, please follow #294
