### ISSUE TITLE
Make WriteAsync accept sbyte[] (Signed byte arrays) aswell.

### ISSUE THREAD

**Issue by Etzix** [xabre/xamarin-bluetooth-le#283]
You should be able to send signed byte arrays as that would help a great deal when communicating with some devices. Right now you are only able to send byte[] if i understand correctly.

Android 4.4+

**Comment by smsissuechecker** [comment]
Hi @Etzix,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!
