### ISSUE TITLE
.NETStandard v2.0 support

### ISSUE THREAD

**Issue by dinodzakmic** [xabre/xamarin-bluetooth-le#285]
By creating new Xamarin.Forms project based on .NETStandard 2.0, Plugin.BLE packages are restored using .NETFramework v4.6.1. 

Rebuilding the solution inside VisualStudio 2017 is successfull, but if I try to set up Jenkins or VS Mobile center for CI/CD/CT, then rebuild fails because of this "issue".
Inside Jenkins I am trying to build using MSBUILD.

Is there any workaround or do you soon plan to add .NETStandard 2.0 support?

**Comment by smsissuechecker** [comment]
Hi @dinodzakmic,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by biapar** [comment]
Do it work with .NETStandard 2.0?

**Comment by dinodzakmic** [comment]
@biapar  It's working when I use my machine for build and deployment, but on my Jenkins server it does not work.

**Comment by biapar** [comment]
Which is the min .NET version supported?

**Comment by smstuebe** [comment]
its using PCL profile 259 which is netstandard1.0. netstandard1.0 is a subset of netstandard2.0. So it will work.

**Comment by flyingxu** [comment]
Plugin.BLE (2.0.0-pre1) is .NETStandard 1.0
```
NETStandard.Library (>= 1.6.1) 
```
