### ISSUE TITLE
StopScanningForDevicesAsync is not working on spesific devices

### ISSUE THREAD

**Issue by MEming** [xabre/xamarin-bluetooth-le#286]
I want to stop the scan before calling a connection request, but the scan does not stop. 

the system is inconsistent because the call is not stopped.

I've only experienced this problem on devices under android version 5.0

Expected
the connection is made after the end of the scan.
Actual
the scan does not end. inconsistent connection.

## Configuration

**Version of the Plugin:** Latest version

**Platform:**  Android 4.4.2

**Device:**  General mobile discovery mini 2

**Comment by smsissuechecker** [comment]
Hi @MEming,

I'm the friendly issue checker.
It seems like (50.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!
