### ISSUE TITLE
Question. How to use example app ?

### ISSUE THREAD

**Issue by Anandks1993** [xabre/xamarin-bluetooth-le#287]
I am newbie to Xamarin and I want to try the example app provided by this plugin. But I don't have an idea how to implement the example. Can someone pls explain how to try out the example app. Thanks is advance 🤝

**Comment by smsissuechecker** [comment]
Hi @Anandks1993,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by flyingxu** [comment]
The best first step to try this is to build the sample from source. You can see there is 1 sample for andoid and 1 for iOS in https://github.com/xabre/xamarin-bluetooth-le/tree/master/Source/BLE.Client .

 	BLE.Client.Droid 	
	BLE.Client.iOS

**Comment by ikebarrett** [comment]
I downloaded and tried the sampl, set configuration to deploy droid.  I get a system.nullreference set.  There is no indication as to why.  Any thoughts on what I am doing wrong?

**Comment by hatefk** [comment]
@flyingxu my understanding is that we have to write two sets of code to get BLE going for both Android and iOS. Am I missing some point or do I need two separate codes for cross platform apps?
