### ISSUE TITLE
Uncaught Exception

### ISSUE THREAD

**Issue by jmilapunk** [xabre/xamarin-bluetooth-le#288]
To help us fix your issue, please provide the information in the below template. If something causes a crash, provide as much information as you can gather.
Just imagine: we do not know what you are doing! 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.

## Steps to reproduce

1.  From Droid project 
Calll var ble = CrossBluetoothLE.Current; 

## Expected behavior
Initialize ble correctly

## Actual behavior
Uncaught Exception Constructor on type ..., 
Freeze Aplication.

### Crashlog
Unhandled Exception:
System.Reflection.TargetInvocationException: <Timeout exceeded getting exception details>

## Configuration

**Version of the Plugin:** e.g. 1.0.0 / 1.0.1-alpha3

**Platform:** e.g.Android 5.1.1

**Device:** e.g. Samsung Grand Prime 

**Code**

```
using Android.Content;
using Android.Telephony;
using Phoneword.Droid;
using System.Linq;
using Xamarin.Forms;
using Uri = Android.Net.Uri;
using Plugin.BLE;

[assembly: Dependency(typeof(PhoneDialer))]
namespace Phoneword.Droid
{
    public class PhoneDialer : IDialer
    {
        public void ScanBluetoothDevices()
        {
            /* var context = MainActivity.Instance;
             if (context == null)
                 return;*/
            if (CrossBluetoothLE.Current != null)
            {
                var ble = CrossBluetoothLE.Current;
            }

            var adapter = CrossBluetoothLE.Current.Adapter;
        }    
    }
}
```

**Comment by smsissuechecker** [comment]
Hi @jmilapunk,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by xabre** [comment]
Use the docs/sample app as guidance. Make sure to install the nuget package in all platform projects.
