### ISSUE TITLE
CrossBluetoothLE.Current.Adapter.DeviceDiscovered is not called

### ISSUE THREAD

**Issue by GO74** [xabre/xamarin-bluetooth-le#292]
Hi, I just tried to scan for my BLE devices on a LG Nexus 5.x. For some reason it didn't discover any. I then loaded the same code to another Device (Samsung A3, Samsung S5) to find out that it works there.

## Steps to reproduce

1. Setup a standard Vanilla with plugin.ble

2. Scan for devices with Samsung A3 - Callbackhandler is called. Scan for devices with Nexus 5x Android 8.1.0 - Callbackhandler is quiet

## Expected behavior
Callbackhandler should be called in Nexus 5.x as well

## Actual behavior
Callbackhandler is not called

### Crashlog
- nothing

## Configuration
Plugin.BLE 1.3.0
Android 8.1.0
LG Nexus 5.x

**Comment by smsissuechecker** [comment]
Hi @GO74,

I'm the friendly issue checker.
It seems like (37.50 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by GO74** [comment]
Okay, I'm still not sure why it happened, but, it's working again. Something with android/ble rights seems to be the cause of the trouble. It was working fine on the very same device two weeks ago...
