### ISSUE TITLE
WriteAsync with cancellation token

### ISSUE THREAD

**Issue by baneageorge** [xabre/xamarin-bluetooth-le#295]
To help us fix your issue, please provide the information in the below template. If something causes a crash, provide as much information as you can gather.
Just imagine: we do not know what you are doing! 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.

## Steps to reproduce

1. Send  in loop messages from android to a Bluetooth device
```
TimeSpan time = new TimeSpan(0, 0, 0, 0, 300); // days, hours, mins, secs, miliseconds
CancellationTokenSource _cancellationTokenSource = new CancellationTokenSource(time);
await WriteCharacteristic.WriteAsync(buffer, _cancellationTokenSource.Token);
```

2. Turn off the Bluetooth device

3. The mobile app waits about 20 seconds before throws disconnected on Android

4. On iOS it blocks indefinitely on the function.

## Expected behaviour
I would expect that using the cancellation token to throw disconnected after 300 milliseconds more or less

## Actual behaviour
The mobile app waits about 10 seconds before throws disconnected

### Crashlog

It is not crashing

## Configuration

Windows 7 visual studio professional 2017 15.5.2, xamarin 4.8.0

**Version of the Plugin:** 1.3.0

**Platform:** Android 5.0 

**Device:** Lenovo S60

**Comment by xabre** [comment]
Related to #245
