### ISSUE TITLE
Update to MvvmCross 6

### ISSUE THREAD

**Issue by fonix232** [xabre/xamarin-bluetooth-le#301]
The latest major release of MvvmCross, version 6.0.0 (well, technically, 6.0.1) was just released. It changes some stuff, most importantly, the countless base libraries were merged into a single assembly.

Unfortunately this project still depends on the old libraries, making it near impossible to be used with 6.0.

The library should be updated to .Net Standard and MvvmCross 6.x

**Comment by smsissuechecker** [comment]
Hi @fonix232,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by flyingxu** [comment]
@fonix232 Thanks, I'd like to see why you say it's near impossible to be used with MvvmCross 6.0

**Comment by flyingxu** [comment]
closed by #307
