### ISSUE TITLE
Impossible to set MTU on iOS

### ISSUE THREAD

**Issue by TheLever** [xabre/xamarin-bluetooth-le#302]
I am having an issue setting the MTU on a BLE device I am using. I have searched the net and talked to the vendor producing the device, and I seem to get conflicting information. Online, I found a post saying that iOS will allow the maximum MTU supported between the phone and the BLE device. Our hardware vendor told me negotiation should be initiated from the master (assuming this is the phone) and that they support higher MTU than the 20 I get now.

Does xamarin-bluetooth-le even support setting the MTU? I tried to track my way down the code and found a statement tracing that setting the MTU is not supported on iOS. This doesn't really jive with what I understand from the post and from our hardware vendor.

Here is the article: https://forums.developer.apple.com/thread/93007

1. On iOS, connect to a BLE device

2. Try to set the MTU and make note of the returned value

3. It seems to be fixed at 20

## Expected behavior
If at all possible on iOS, it should set the MTU.

## Actual behavior
Returns 20 always.

## Configuration

**Version of the Plugin:** e.g. 1.30.0

**Platform:** iOS 11.3

**Device:** iPhone 7 Plus, iPhone 5

**Comment by esskar** [comment]
@TheLever From the link you referenced in your post

> There is **no** open iOS API to request an MTU change/update. Instead, this request would need to be initiated by the peripheral.

As i understand, iOS will negotiate the supported MTU when the device is supports negotiation, if not, then not and it will fallback of 20!?

**Comment by JoeBakalor** [comment]
iOS will does negotiate the MTU automatically, it simply uses the largest MTU supported by both devices.
