### ISSUE TITLE
i can find my device ,but i can't connect to the device when i use the method ConnectToDeviceAsync

### ISSUE THREAD

**Issue by kobin97** [xabre/xamarin-bluetooth-le#306]
To help us fix your issue, please provide the information in the below template. If something causes a crash, provide as much information as you can gather.
Just imagine: we do not know what you are doing! 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.

## Steps to reproduce

1.

2.

3.

## Expected behavior
Tell us what should happen

## Actual behavior
Tell us what happens instead

### Crashlog

If something causes an exception paste full stack trace + Exception here

## Configuration

**Version of the Plugin:** e.g. 1.0.0 / 1.0.1-alpha3

**Platform:** e.g. iOS 10.1 / Android 4.4 / ... (including version!!! e.g. Android 5.1 / i0S 10)

**Device:** e.g. HTC Sensation /i Phone 7 ...

**Comment by smsissuechecker** [comment]
Hi @kobin97,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by kobin97** [comment]
public HeaderControlSample()
        {
            InitializeComponent();

var ble = CrossBluetoothLE.Current;
            var adapter = CrossBluetoothLE.Current.Adapter;

            adapter.DeviceConnected += Adapter_DeviceConnected;

            adapter.DeviceDiscovered += (s, a) =>
            {
                if (a.Device.Name != null)
                {
                    devicelist1.Add(a.Device);
                 
                }

            };

            await adapter.StartScanningForDevicesAsync();
            
            lv_deviceList.ItemsSource = devicelist1;

        }

 async public void OnSelection(object sender, SelectedItemChangedEventArgs e)
        {

            var DeviceSelect = e.SelectedItem as IDevice;
            var answer = await DisplayAlert("Device Connection", "Would you like to connect with this device:" + DeviceSelect.Name.ToString() + "?", "Yes", "No");


            if (answer)
            {
                try
                {
                    await CrossBluetoothLE.Current.Adapter.StopScanningForDevicesAsync();

                    await CrossBluetoothLE.Current.Adapter.ConnectToDeviceAsync(DeviceSelect);
                }
                catch (DeviceConnectionException ex)
                {
                    System.Diagnostics.Debug.WriteLine("EXCEPTION\nDevice : " + ex.ToString());
                }
            }


        }

**Comment by kobin97** [comment]
when is use the method "ConnectToDeviceAsync",nothing happen,the device state is always "Disconnected"

**Comment by jeevaeastpoint** [comment]
Have you checked whether "DeviceConnected" event is fired on connecting to the device?

**Comment by xabre** [comment]
Not reproducible with sample app. Not enough information. Reopen issue if still a problem and add details.
