### ISSUE TITLE
How to handle GATT write errors more efficiently

### ISSUE THREAD

**Issue by Rousseau38** [xabre/xamarin-bluetooth-le#309]
Hello, 

How do you guys handle, resolve Gatt writeasync errors with this package? I read earlier posts and followed android guidelines (don't scan while connected, write on the main thread), but I still receive the errors. 

Here is how I writeasync: 

    await OnMainThreadAsync(async () =>
                                    {
                                        await device.characteristic.WriteAsync(array);                                                      
                                    });

Here is OnMainThreadAsync: 

        public static async Task OnMainThreadAsync(Func<Task> action)
        {
            var tcs = new TaskCompletionSource<object>();
            Xamarin.Forms.Device.BeginInvokeOnMainThread(async () => {
                try
                {
                    await action();
                    tcs.SetResult(new { });
                }
                catch (Exception ex)
                {
                    tcs.SetException(ex);
                }
            });
            await tcs.Task;
        }

Thanks

**Comment by smsissuechecker** [comment]
Hi @Rousseau38,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by xabre** [comment]
Also make sure to queue your write requests especially on Android. Several concurrent write requests will lead to GATT 133 errors.

**Comment by Umer-Mahmood** [comment]
> Also make sure to queue your write requests especially on Android. Several concurrent write requests will lead to GATT 133 errors.

How to queue?
