### ISSUE TITLE
GetServiceAsync returns Task and thus needs to be awaited

### ISSUE THREAD

**Issue by nviswanath24** [xabre/xamarin-bluetooth-le#312]
## Steps to reproduce

1. https://github.com/didourebai/BLEPluginDemo/tree/master/Workshop - use the code from this repo

2. In BLEPluginDemo/Workshop/Workshop/Views/DeviceView.xaml.cs replace private async void btnGetServices_Clicked as follows:

        private async void btnGetServices_Clicked(object sender, EventArgs e)
        {
           
            Service = device.GetServiceAsync(device.Id);

        }

3.

## Expected behavior
It should work and then the - 
characteristic =  Service.GetCharacteristicAsync(Guid.Parse("guid")); should work successfully.

## Actual behavior
Shows this error : 
Error CS0266: Cannot implicitly convert type 'System.Threading.Tasks.Task<Plugin.BLE.Abstractions.Contracts.IService>' to 'Plugin.BLE.Abstractions.Contracts.IService'. An explicit conversion exists (are you missing a cast?) (CS0266) 

### Crashlog

If something causes an exception paste full stack trace + Exception here

## Configuration

**Version of the Plugin:** 1.3.0

**Platform:** Android API 27

**Device:** Google Pixel 2

**Comment by smsissuechecker** [comment]
Hi @nviswanath24,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by fonix232** [comment]
@nviswanath24 `GetServiceAsync` as the name suggests, is an `async` process. You need to add await to it:

    
```
  private async void btnGetServices_Clicked(object sender, EventArgs e)
 {
     Service = await device.GetServiceAsync(device.Id);
 }
```
