### ISSUE TITLE
Sample project generates system.nullreferenceobject

### ISSUE THREAD

**Issue by ikebarrett** [xabre/xamarin-bluetooth-le#313]
To help us fix your issue, please provide the information in the below template. If something causes a crash, provide as much information as you can gather.
Just imagine: we do not know what you are doing! 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.

## Steps to reproduce

1. Clone file

2. Set Droid to deploy in configuration manager

3. Build and launch 

## Expected behavior
Should run properly

## Actual behavior
Loads for a second, then crashes.

### Crashlog

06-17 12:39:03.890 I/MonoDroid( 3271): System.NullReferenceException: Object reference not set to an instance of an object.
06-17 12:39:03.890 I/MonoDroid( 3271):   at BluetoothLE.Droid.Adapter+<StartScanningForDevices>d__21.MoveNext () [0x000e2] in C:\FitnessAppinfo\Xamarin.BluetoothLE-master\Xamarin.BluetoothLE-master\BluetoothLE.Droid\Adapter.cs:93 
06-17 12:39:03.890 I/MonoDroid( 3271): --- End of stack trace from previous location where exception was thrown ---

## Configuration

**Version of the Plugin:** current

**Platform:** Android 7.1 (all actually)

**Device:** Android 7.1 emulator

**Comment by smsissuechecker** [comment]
Hi @ikebarrett,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by ikebarrett** [comment]
For those that are new to Xamarin...I found this this morning.  Appearantly you can't use your emulator to test Bluetooth.

https://stackoverflow.com/questions/2175076/how-to-use-bluetooth-in-android-emulator
