### ISSUE TITLE
High Android Battery Usage After StartUpdatesAsync on characteristic (no data).

### ISSUE THREAD

**Issue by veletron2** [xabre/xamarin-bluetooth-le#315]
Hi

My App (on Android currently, iOS later) contains a Service which uses a single characteristic contained within the only service that my device advertises. The service is an Android Foreground Service, Android target SDK is 8.1. The test devices are Android 7.1 and 8.0. The use of a foreground service was forced by the changes in Android 8+.

All works fine, apart from battery usage, and I wondered if anyone here had any tips on that front.

If I start my app and call StartUpdatesAsync() then 50% of the battery will be consumed overnight by the app with no BLE traffic from the connected device.

If I remove the call to StartUpdatesAsync() as such killing the listener then the App will only consume 1% battery overnight.

My App requires a 'constant' connection to the peripheral which is a body-worn medical device. Is what I am experiencing normal? Is there a reasonable route around it? At the moment I am thinking that the app will need to use a the alarm manager to periodically force a check for data on my characteristic every few seconds manually?

## Steps to reproduce

1. Connect to device

2. Get the BLE Service

3. Get the Characteristic and call StartUpdatesAsync() on it

## Expected behavior
Normal battery use (no data on BLE characteristic)

## Actual behavior
High data useage - 50% battery consumed overnight with no BLE traffic

## Configuration

**Version of the Plugin:**  1.3.0

**Platform:** e.g. Android 7.1 and 8.1 

**Device:** Samsung Galaxy S7 and Samsung Note 8

**Comment by smsissuechecker** [comment]
Hi @veletron2,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by flyingxu** [comment]
This is expected. When people say Bluetooth **Low Energy**, it means the peripheral is low energy. If you have a phone constantly scan or keep a long running connection, the phone will not be low energy.
