### ISSUE TITLE
Connected to bluetooth device but has no idea what to do next

### ISSUE THREAD

**Issue by kelvin195eclipse** [xabre/xamarin-bluetooth-le#317]
Hi guys,

I am new to bluetooth feature development and currently working on an application which will print receipts generated from the app. I knew that my test printer supports BLE 4.0 (Mustek MK380) and I found this plugin. 

I am able to connect to the device, but I have no idea what to do next.

Could anyone provide me some directions on what to do next / research for in order to understand how should I utilize this plugin to print receipt from my PCL app.

Thank you!

**Comment by smsissuechecker** [comment]
Hi @kelvin195eclipse,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!
