### ISSUE TITLE
CrossBluetoothLE does not exist in the current context

### ISSUE THREAD

**Issue by bleari** [xabre/xamarin-bluetooth-le#318]
Error appears when I type this line "var ble = CrossBluetoothLE.Current;"

Is the package not installed correctly? This is my first time using GitHub and packages. I added the permissions in the manifest.

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'CrossBluetoothLE' does not exist in the current context	BLE_Test.Android	C:\Users\lukem\Documents\Visual Studio 2017\Projects\BLE Test\BLE Test\BLE_Test.Android\MainActivity.cs	24	Active

Code added below:

protected override void OnCreate(Bundle bundle)
        {
            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;

            base.OnCreate(bundle);

            global::Xamarin.Forms.Forms.Init(this, bundle);
            LoadApplication(new App());
            var ble = CrossBluetoothLE.Current;
            var adapter = CrossBluetoothLE.Current.Adapter;
            var state = ble.State;
            ble.StateChanged += (s, e) =>
            {
                Debug.WriteLine($"The bluetooth state changed to {e.NewState}");
            };
            adapter.DeviceDiscovered += (s, a) => deviceList.Add(a.Device);
            await adapter.StartScanningForDevicesAsync();

 **various other errors also occur**
**Platform:** Android 4.4 / Android 7.1)

Thanks

**Comment by smsissuechecker** [comment]
Hi @bleari,

I'm the friendly issue checker.
It seems like (87.50 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!
