### ISSUE TITLE
Build error on Mac 

### ISSUE THREAD

**Issue by flyingxu** [xabre/xamarin-bluetooth-le#319]
To help us fix your issue, please provide the information in the below template. If something causes a crash, provide as much information as you can gather.
Just imagine: we do not know what you are doing! 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.

## Steps to reproduce

1. cd ./build

2. chmod 755 ./build.sh

3. ./build.sh

## Expected behavior
build ok

## Actual behavior
build failed

### Crashlog

++ export FVersion=4.10.5
++ FVersion=4.10.5
++ mono --runtime=v4.0 ../Source/.nuget/nuget.exe install FAKE -Version 4.10.5
Feeds used:
  /Users/fei/.nuget/packages/
  https://api.nuget.org/v3/index.json
  /Users/fei/Documents/github/xamarin-bluetooth-le

Package "FAKE.4.10.5" is already installed.
++ mono --runtime=v4.0 ../Source/.nuget/nuget.exe install xunit.runner.console -Version 2.1.0
Feeds used:
  /Users/fei/.nuget/packages/
  https://api.nuget.org/v3/index.json
  /Users/fei/Documents/github/xamarin-bluetooth-le

Package "xunit.runner.console.2.1.0" is already installed.
++ mono --runtime=v4.0 FAKE.4.10.5/tools/FAKE.exe build.fsx
**System.NullReferenceException: Object reference not set to an instance of an object
  at Fake.FSIHelper.runFAKEScriptWithFsiArgsAndRedirectMessages (System.Boolean printDetails, Fake.FSIHelper+FsiArgs _arg1, System.Collections.Generic.IEnumerable`1[T] env, Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] onErrMsg, Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] onOutMsg, System.Boolean useCache, System.Boolean cleanCache) [0x00229] in <566eee98ccf1c534a745038398ee6e56>:0**

**Comment by smsissuechecker** [comment]
Hi @flyingxu,

I'm the friendly issue checker.
It seems like (50.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by xabre** [comment]
Moved to cake with 2.0.0
