### ISSUE TITLE
NativeDevice.Rssi, State and Id properties not found

### ISSUE THREAD

**Issue by asierdanjou** [xabre/xamarin-bluetooth-le#326]
In the Xmal code:

                                _<Label
                                    FontAttributes="Bold"
                                    Text="{Binding NativeDevice.Name}">
                                </Label>
                                <Label
                                    Text="{Binding NativeDevice.Rssi}">
                                </Label>
                                <Label
                                    FontAttributes="Italic"
                                    Text="{Binding NativeDevice.Address}">
                                </Label>
                                <Label
                                    FontAttributes="Bold"
                                    Text="{Binding NativeDevice.State}">
                                </Label>_

But in the output window:

_[0:] Binding: 'Rssi' property not found on '00:0B:57:EF:2D:90', target property: 'Xamarin.Forms.Label.Text'
[0:] Binding: 'State' property not found on '00:0B:57:EF:2D:90', target property: 'Xamarin.Forms.Label.Text'_

When I'm tiping code nativeDevice property (IDevice) it shows me State and Rssi options but then when executing it does not find these properties. Any helping ?

**Comment by smsissuechecker** [comment]
Hi @asierdanjou,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by MKuckert** [comment]
Is a linker in your project enabled?

**Comment by xabre** [comment]
Ensure your binding sources are correct. Check the sample project. Works fine,
