### ISSUE TITLE
Visualization Error Constructor on type 'InterpretedAndroid.Content.BroadcastReceiver' not found. (MissingMethodException)

### ISSUE THREAD

**Issue by bayuprmbd** [xabre/xamarin-bluetooth-le#327]
I just try to make simple code to my apps. I follow Plugin.Ble tutorial. But, when I try to deploy to my phone (Mi A1 Android 8.1) always error.

`using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;
using Plugin.BLE.Abstractions.Contracts;
using Plugin.BLE;

namespace App14
{
	public partial class MainPage : ContentPage
	{
        IBluetoothLE ble;
        IAdapter adapter;
		public MainPage()
		{
			InitializeComponent();
            adapter = CrossBluetoothLE.Current.Adapter;
            ble = CrossBluetoothLE.Current;
		}
	}
}
`

I'm new on Xamarin. Please Help me

**Comment by smsissuechecker** [comment]
Hi @bayuprmbd,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!
