### ISSUE TITLE
Get the rssi of a device that have a specific name without connecting to it

### ISSUE THREAD

**Issue by Jaguerre** [xabre/xamarin-bluetooth-le#328]
## Code attached bellow

        private void OnButtonClicked(object sender, EventArgs e)
        {
            
            deviceList.Clear();
            try
            {
                
                adapter.DeviceDiscovered += (s, a) =>
                {
                    if (a.Device.Name != null)
                    {
                        deviceList.Add(a.Device);
                    }
                    
                };
                if (!ble.Adapter.IsScanning)
                {
                    adapter.StartScanningForDevicesAsync();
                }
            }
            catch (Exception ex)
            {
                DisplayAlert("Attention", ex.Message.ToString(), "Erreur!");
            }

            var one = deviceList.Where(x => x.Name == "BLE #1");
            device = one.FirstOrDefault() as IDevice;
            var rssi = device.Rssi;

        }

What I would like to do is do a scanning in the background, then if I'm in range of a device that holds a specific name, an alert is displayed.

I would like few user interactions as possible so nothing in the xaml except a button to launch the scan.

Please be lenient, I'm new to this world.

## Steps to reproduce

1. Do a background scanning

2. Search into the deviceList, the specific device

3. Get the rssi from the device

## Expected behavior
The deviceList should have few devices into it

## Actual behavior
The deviceList is empty

### Crashlog

If something causes an exception paste full stack trace + Exception here

## Configuration

**Version of the Plugin:** e.g. 1.0.0 / 1.0.1-alpha3

**Platform:** e.g. iOS 10.1 / Android 4.4 / ... (including version!!! e.g. Android 5.1 / i0S 10)

**Device:** e.g. HTC Sensation /i Phone 7 ...

**Comment by Eric-EvilTwin** [comment]
I'm just getting started with this nuget package, but I'm pretty sure you need to `await` where you call `adapter.StartScanningForDevicesAsync();` So I think you'll need 

`await adapter.StartScanningForDevicesAsync();` 

Then you'll need to add `async` your method. If you're not familiar with that in C#, there are tons of sites to explain it thoroughly if you Google it.

**Comment by simonyang2002** [comment]
I am new to this stuff.
Can somebody tell me what this code is written in and what platform this runs in

**Comment by Jaguerre** [comment]
You are right @Eric-EvilTwin but it doesn't fix the problem that is: The deviceList is not filled when a device is discovered.

-----

It's written in C#, it's crossplatform (Android, IOS) and I'm using Xamarin @simonyang2002 I hope I answered your question.

**Comment by simonyang2002** [comment]
thanks everybody

**Comment by Jaguerre** [comment]
Yeah, I always check the permissions when I test my app. The thing is when I use a ListView then put ListView.ItemsSource = DeviceList, it works.

**Comment by flyingxu** [comment]
@Jaguerre It seemed that you have fixed your issue. I will close this issue. Feel free to reopen it if you still have problems.

**Comment by Jaguerre** [comment]
@flyingxu No my issue is not fixed, because what I want to do is: not having a listView in my xaml, I want want the deviceList in my code behind filled without the user seeing it.
