### ISSUE TITLE
How to get a pulse?

### ISSUE THREAD

**Issue by StriBog45** [xabre/xamarin-bluetooth-le#333]
My goal is to get data from the fitness bracelet Torntisc T1 using my application and independently process data from the bracelet

To implement I use Xamarin and found a Bluetooth LE plugin for Xamarin plugin to connect to the device and receive data from it. However, all the characteristics obtained are called "Unknow characteristic" and in values ​​of 0 bytes. Although it has 5 services, each of which has 3 characteristics. The only name of characteristics in 1 service is other: "Device Name", "Appearance", "Peripheral Preferred Connection Parameters". However, the value (value) is everywhere 0 bytes. How to get characteristics? How to get a pulse?

To the bracelet there is an application H Band 2.0, which shows a fairly large number of settings for the bracelet, the question arises where is all this?

```
foreach (var TestService in Services)
            {
                var characteristics = await TestService.GetCharacteristicsAsync();
                foreach (var Characteristic in characteristics)
                {
                    var properties = Characteristic.Properties;
                    var name = Characteristic.Name;
                    var serv = Characteristic.Service;
                    var value = Characteristic.Value;
                    var stringValue = value.ToString();
                    string result = "";
                    if (value.Length != 0)
                        result = System.Text.Encoding.UTF8.GetString(value, 0, value.Length - 1);
                }
            }
```

[stackoferflow](https://stackoverflow.com/questions/53033063/xamarinandroid-how-to-get-data-from-the-bracelet-via-bluetooth)

## Configuration

**Version of the Plugin:** 1.3.0

**Platform:** Android 6.0

**Device:** [Torntisc T1 Bluetooth Heart Rate Smart Wristband](https://ru.aliexpress.com/item/Smart-Band/32809885498.html?spm=a2g0v.10010108.1000016/B.1.454b18f5cxtYEj&isOrigTitle=true)

**Comment by flyingxu** [comment]
Could you share the output of your code above?
The device might have private service / characteristics.

**Comment by StriBog45** [comment]
> Could you share the output of your code above?
> The device might have private service / characteristics.
[screen](https://i.stack.imgur.com/HEH0m.png)

As i said before, characteristics obtained are called "Unknown characteristic" and in values ​​of 0 bytes.

**Comment by xabre** [comment]
All characteristics are "Unknown" except the ones defined here: https://www.bluetooth.com/specifications/gatt/characteristics/, these are included in the plugin in `KnownCharacteristics.cs`.

After discovering charcteristics for a service (`await TestService.GetCharacteristicsAsync();`) you first have to call `var bytes = await characteristic.ReadAsync()` before anything is set in characteristic.Value otherwise value will be null.

Will close issue. Feel free to follow up if new questions arise.
