### ISSUE TITLE
StartScanningForDevicesAsync() time limit

### ISSUE THREAD

**Issue by dfclark** [xabre/xamarin-bluetooth-le#335]
StartScanningForDevicesAsync() appears to have a default timeout value of 10 seconds (10000 milliseconds).  My app needs to have scanning running indefinitely - is there a way to set the timeout to essentially infinity or unlimited?

## Steps to reproduce

1. Call StartScanningForDevicesAsync()

2. Roughly 10 seconds later scanning stops

## Expected behavior
App should be able to invoke StartScanningForDevicesAsync() and have it continue to scan until app invokes StopScanningForDevicesAsync().

## Actual behavior
Roughly 10 seconds after invocation of xxx scanning stops

### Crashlog

If something causes an exception paste full stack trace + Exception here

## Configuration

**Version of the Plugin:** e.g. 1.0.0 / 1.0.1-alpha3
1.3.0

**Platform:** e.g. iOS 10.1 / Android 4.4 / ... (including version!!! e.g. Android 5.1 / i0S 10)
Xamarin/Android 8.1.0 (API 27)

**Device:** e.g. HTC Sensation /i Phone 7 ...
Pixel C tablet

**Comment by smsissuechecker** [comment]
Hi @dfclark,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by xabre** [comment]
You can chnge the timeout by using the Adapter.ScanTimeout method. Though it's not recommended to do that.

```
       /// <summary>
        /// Timeout for Ble scanning. Default is 10000.
        /// </summary>
        int ScanTimeout { get; set; }
```
