### ISSUE TITLE
Unable to connect to iPhone XS

### ISSUE THREAD

**Issue by slimjim10** [xabre/xamarin-bluetooth-le#337]
Unable to connect to an iPhone XS using `await _adapter.ConnectToDeviceAsync(device);` or `await _adapter.ConnectToKnownDeviceAsync(deviceGuid);` (I have tried both). Using either method does not return nor throws an exception, similar behavior as if the BLE device is turned off. I can connect to the BLE device with all other smartphones I have tried (both Android and other iOS devices).

## Steps to reproduce

1. Try connecting to an iPhone XS using `await _adapter.ConnectToDeviceAsync(device);`

## Expected behavior
Get an event from OnDeviceConnected() or an exception.

## Actual behavior
The method call does not return at all. Similar behavior as when trying to connect with an iOS device to a BLE device that is turned off.

## Configuration

**Version of the Plugin:** 1.3.0 and 2.0.0-pre1 (I have tried both).

**Platform:** iOS 12.1 (16B92)

**Device:** iPhone XS

**Comment by smsissuechecker** [comment]
Hi @slimjim10,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by slimjim10** [comment]
Do you know if this is something you will look into? If so, do you know when?

I am using this in a project which needs to be available on the app/play store in January, and would really appreciate if you can let me know what you think will happen with this issue. Otherwise I need to try to find another solution. :)

Best regards Jim

**Comment by slimjim10** [comment]
It was a mistake on our side. We are connecting to a BLE peripheral that we are developing as well, and we were unable to connect to it with an iPhone XS when using other BLE apps.
