### ISSUE TITLE
Release v2.0.0-pre2 to nuget

### ISSUE THREAD

**Issue by flyingxu** [xabre/xamarin-bluetooth-le#338]
The current 2.0.0 branch has some update from v2.0.0-pre1, the main update is the removal of MvvmCross5 and compatibility of MvvmCross6.

It's actually a good time to release it to nuget as pre2. Currently, I have to locally compile it and then use it with a MvvmCross  6 project.

**Comment by smsissuechecker** [comment]
Hi @flyingxu,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by flyingxu** [comment]
@xabre @smstuebe

**Comment by JPSiller** [comment]
+1 BLE functionality broken after upgrading to latest MvvmCross.

**Comment by JPSiller** [comment]
Hi @flyingxu Do you have an estimate when this will be released to nuget? 

Thanks

**Comment by ahi** [comment]
It would be nice to see the changes from [826e066](https://github.com/xabre/xamarin-bluetooth-le/commit/826e066d70f3e1b561340a3193fbdb0b0df77a20) in nuget. Are there any plans for a new release?

**Comment by xabre** [comment]
Will do a release this weekend hopefully :)

**Comment by xabre** [comment]
published 2.0.1 and 2.1.0-pre.1
