### ISSUE TITLE
Issue with DeviceConnectionLost event

### ISSUE THREAD

**Issue by asierdanjou** [xabre/xamarin-bluetooth-le#340]
We have a MainPage where it gets connect to a peripheral (_device = await adapter.ConnectToKnownDeviceAsync(Guid.Parse("00000000-0000-0000-0000-" + address));_)  and if it is success then a second page (MyPage) is openned with next code:
_await Application.Current.MainPage.Navigation.PushAsync(new MainTabbedPage(adapter, device, dispo.Nombre));_
We describe lost connection event in the constructor of MyPage as follows:
_public MyPage(IAdapter adapterin, IDevice devicein, string ChannelName)
    {
        InitializeComponent();
        adapter = adapterin;
        device = devicein;
        LabelChannelName.Text = ChannelName;

        adapter.DeviceConnectionLost += (s, e) =>
        {
            Debug.WriteLine($"LOST CONNECTION: {e.Device.Name}");
            adapter.DeviceConnectionLost -= null;
            Device.BeginInvokeOnMainThread(() =>
            {
                this.Navigation.PopAsync();
            });
            Debug.WriteLine($"LOST CONNECTION.");
        };
    }_

## Steps to reproduce

1. Connect to a ble peripheral with ConnectToKnownDeviceAsync function.

2. Open a second page with PushAsync and define adapter.DeviceConnectionLost in its constructor.

3. Turn off  ble peripheral's supply to produce a lost connection.

4. Wait lost connection happens.

5. Do Navigation.PopAsync in DeviceConnectionLost event, to get back to MainPage.

6. Turn on peripheral again.

7. Repeat again steps from 1 to 5. When doing that second time we will get a Unhandled Exception cause DeviceConnectionLost event is reached twice instead of only once.

## Expected behavior
When DeviceConnectionLost event happens it only must go once to event code.

## Actual behavior
When DeviceConnectionLost event happens it goes twice to event code.

### Crashlog
01-09 20:50:04.544 D/BluetoothGatt(24643): onClientConnectionState() - status=8 clientIf=6 device=90:FD:9F:D0:6D:65
01-09 20:50:04.624 D/BluetoothGatt(24643): close()
01-09 20:50:04.624 D/BluetoothGatt(24643): unregisterApp() - mClientIf=6
[0:] LOST CONNECTION: name3
[0:] LOST CONNECTION: name3
[0:] LOST CONNECTION.
[0:] LOST CONNECTION: name3
[0:] LOST CONNECTION.
Unhandled Exception:

System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

## Configuration

Version of the Plugin: 1.3.0

Platform:  Android 5.0 

Device: Samsung Galaxy S4

**Comment by smsissuechecker** [comment]
Hi @asierdanjou,

I'm the friendly issue checker.
It seems like (37.50 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by asierdanjou** [comment]
Fixed with next code:

        protected override void OnDisappearing()
        {
            base.OnDisappearing();
            adapter.DeviceConnectionLost -= lostEvent;
            Debug.WriteLine($"ON DISAPPEARING");
        }

Thanks,
Asier.
