### ISSUE TITLE
Question on characteristic.WriteAsync() on iOS and Android

### ISSUE THREAD

**Issue by wangguan1888** [xabre/xamarin-bluetooth-le#343]
Hello

I'm trying to send command to BLE device.
I have a problem about characteristic.WriteAsync() on iOS and Android.
I will show detail in the following Steps.

## Steps to reproduce
1.var service = await device.GetServiceAsync(Guid.Parse(My ID)); //Get Service
2.var characteristic = await service.GetCharacteristicAsync(Guid.Parse(My ID)); //Get Characteristic
3.var sendresult = await characteristic.WriteAsync(byte[]{0x01, 0x02, 0x03, 0x04, 0x05}); //Write Data
4.After step 3, I found sendresult is true, but args.Characteristic.Value is null. After sending mydata for 4 times, args.Characteristic.Value has data.

## Expected behavior
I would like to send my data to BLE device only one time and get response soon.

## Actual behavior
Send my data 4 times and receive response.

### Crashlog
Nothing

## Configuration
**Version of the Plugin:2.0.0-pre1
**Platform: iOS 12.1 / Android 7.1
**Device: iPhone XR / Asus Android

**Comment by smsissuechecker** [comment]
Hi @wangguan1888,

I'm the friendly issue checker.
It seems like (37.50 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!
