### ISSUE TITLE
ValueUpdated callback never fired for Notify Property

### ISSUE THREAD

**Issue by Noufalt** [xabre/xamarin-bluetooth-le#344]
I am trying sample code available with the plugin and trying to read Characteristics from Thermometer , Blood Pressure device & Blood Glucose Monitor system .Thermometer & BP device I could able read the Temperature, Blood Pressure Measurement characteristics when I click StartUpdate from the Characteristics Details screen . But for Blood Glucose Monitor device->I am trying to read Glucose Measurement Characteristics and the property mentioned as Notify ,  I am not able to see the value when I press startUpdate .The only difference I found as per GATT specification  (https://www.bluetooth.com/specifications/gatt/viewer?attributeXmlFile=org.bluetooth.service.glucose.xml) is Property mentioned for Glucose Measurement is "Notify" where as for Blood pressure service->Blood Pressure Measurement characteristics has Indicate property . For Notify Property ValueUpdated callback is not firing . 

Can some one help on this .

## Steps to reproduce

1.Open the sample application available with the plugin , Discover & connect Blood Glucose Device

2.Click on Glucose Service 

3.Click on Glucose Measurement Characteristics and click details

4.Click start Updates 

## Expected behavior
I could see Blood Sugar value in Device , so when I press start update GlucoseMeasurement characteristics Hex value should see

## Actual behavior
I can't see the Hexadecimal value when I press start update ( Blood pressure device is connected & paired , I can see Blood pressure values with BP device ) 

### Crashlog
No crashes or exceptions.

## Configuration
**Platform:** e.g. It happens for iOS & Android 
**Device:** e.g. Samsung S7 /i Phone 6 ...

**Comment by smsissuechecker** [comment]
Hi @Noufalt,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by xabre** [comment]
Please try the sample app and see if it still happens.
