### ISSUE TITLE
On App start with visual studio, got only a error

### ISSUE THREAD

**Issue by harrypotter06** [xabre/xamarin-bluetooth-le#349]
To help us fix your issue, please provide the information in the below template. If something causes a crash, provide as much information as you can gather.
Just imagine: we do not know what you are doing! 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.

## Steps to reproduce

1. Load Project

2. Start Project in Debug Mode

3. The App- Icon is show.
4. After (tested on single stepp) this (MainApplication.cs):
public void OnActivityResumed(Activity activity)
{
CrossCurrentActivity.Current.Activity = activity;
}
"CrossCurrentActivity.Current.Activity = activity;" works (activity has value:"{md5284d34c42aded56ab4276d9b253081c8.SplashScreen@7e07a0f}")
5. After "Next Stepp" on "}" i got the error.
But i tested on Emulator with Android 7, 8 and also on Device with Android 9

## Expected behavior
That the App works on emulator or physical device

## Actual behavior
Unhandled Exception:
System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.

### Crashlog

03-24 22:35:47.065 D/Mono (24630): Assembly Ref addref MvvmCross.Binding.Droid[0x72297dbf80] -> MvvmCross.Platform.Droid[0x721d47c680]: 3
03-24 22:35:47.086 D/AwareBitmapCacher(24630): handleInit switch not opened pid=24630
03-24 22:35:47.091 D/Mono (24630): Assembly Ref addref BLE.Client.Droid[0x72297db180] -> AndHUD[0x72297db580]: 2
03-24 22:35:47.092 D/Mono (24630): Assembly Ref addref BLE.Client.Droid[0x72297db180] -> MvvmCross.Binding.Droid[0x72297dbf80]: 3
03-24 22:35:47.093 D/Mono (24630): Assembly Ref addref BLE.Client.Droid[0x72297db180] -> Splat[0x721d47ce00]: 2
03-24 22:35:47.111 D/Mono (24630): Unloading image System.Reflection.dll [0x7203ad4000].
03-24 22:35:47.112 D/Mono (24630): Image addref System.Reflection[0x7203b1b680] -> System.Reflection.dll[0x7204e7f000]: 7
03-24 22:35:47.112 D/Mono (24630): Config attempting to parse: 'System.Reflection.dll.config'.
03-24 22:35:47.112 D/Mono (24630): Config attempting to parse: '/Users/builder/jenkins/workspace/xamarin-android-d15-9/xamarin-android/external/mono/sdks/out/android-arm64-v8a-release/etc/mono/assemblies/System.Reflection/System.Reflection.config'.
03-24 22:35:47.112 D/Mono (24630): Assembly Ref addref MvvmCross.Binding[0x72297dbe80] -> System.Reflection[0x720bdc9580]: 5
03-24 22:35:47.124 D/Mono (24630): Unloading image System.Linq.dll [0x7203ad4000].
03-24 22:35:47.124 D/Mono (24630): Image addref System.Linq[0x7203b2af00] -> System.Linq.dll[0x7204ea0000]: 7
03-24 22:35:47.124 D/Mono (24630): Config attempting to parse: 'System.Linq.dll.config'.
03-24 22:35:47.124 D/Mono (24630): Config attempting to parse: '/Users/builder/jenkins/workspace/xamarin-android-d15-9/xamarin-android/external/mono/sdks/out/android-arm64-v8a-release/etc/mono/assemblies/System.Linq/System.Linq.config'.
03-24 22:35:47.124 D/Mono (24630): Assembly Ref addref MvvmCross.Binding[0x72297dbe80] -> System.Linq[0x7204faa080]: 5
Unhandled Exception:
System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.

## Configuration

Visual Studio 2017 with last patchlevel on Windows 10 with Build 1809

**Comment by smsissuechecker** [comment]
Hi @harrypotter06,

I'm the friendly issue checker.
It seems like (37.50 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by xabre** [comment]
Give 2.0.1 or 2.1.0-pre.1 a try.
We have never tested or supported emulator/simulator.
