### ISSUE TITLE
reference source code instead of nuget package

### ISSUE THREAD

**Issue by Crunch91** [xabre/xamarin-bluetooth-le#350]
To help us fix your issue, please provide the information in the below template. If something causes a crash, provide as much information as you can gather.
Just imagine: we do not know what you are doing! 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.

I have a bluetooth device which returns a specific bluetooth service for a given UUID. On android this works but not on iOS. I have to debug the plugin to see if the plugin causes this issue or the bluetooth device itself. Since now I just referenced the nuget package to my productive code. Now I want to reference the cloned source code of the project to debug properly. Your sample app uses MvvmCross but I don't want to. According to your project description and some closed issues this should be possible without MvvmCross.
Issue #131 describes nearly the same error but he tried to make it work with MvvmCross and he did not explain exactly how to make it run.

## Steps to reproduce

1. setup new Xamarin Forms project

2. clone  github repo (https://github.com/xabre/xamarin-bluetooth-le)

3. add following references:

    - shared/main project:
      - Plugin.BLE
      - Plugin.BLE.Absractions

    - Android project:
      - Plugin.BLE
      - Plugin.BLE.Absractions
      - Plugin.BLE.Android

    - iOS project
      - Plugin.BLE
      - Plugin.BLE.Absractions
      - Plugin.BLE.iOS

4. start android project on physical android device

## Expected behavior
`CrossBluetoothLE.Current` should return the android implementation of `IBluetoothLE`

## Actual behavior
`CrossBluetoothLE` throwing exception because following code returns null:

```
 static IBluetoothLE CreateImplementation()
        {
#if PORTABLE
            return null;
#else
            var implementation = new BleImplementation();
            implementation.Initialize();
            return implementation;
#endif
        }
```

### Crashlog

Exception:

System.NotImplementedException: This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation. occurred

## Configuration

**Version of the Plugin:** 2.0.0-pre1

**Platform:** Android 5.0.1

**Device:** Samsung S4

**Comment by smsissuechecker** [comment]
Hi @Crunch91,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by xabre** [comment]
Don't reference Plugin.BLE
