### ISSUE TITLE
Crash on Device disconnected while fetching services on Android 9.0

### ISSUE THREAD

**Issue by tqngan1984** [xabre/xamarin-bluetooth-le#352]
This issue happened in Fabric

![Screen Shot 2019-04-05 at 10 38 57 AM](https://user-images.githubusercontent.com/1107856/55602530-508f8180-5790-11e9-8eff-56b0c03db5ca.png)

### Crashlog

Non-fatal Exception: java.lang.Throwable: Device Perifit(o) disconnected while fetching services.
       at Plugin.BLE.Abstractions.Utils.TaskBuilder+<FromEvent>d__1`3[TReturn,TEventHandler,TRejectHandler].MoveNext ()(filename unknown)
       at Plugin.BLE.Android.Device+<GetServicesNativeAsync>d__14.MoveNext ()(filename unknown)
       at Plugin.BLE.Abstractions.DeviceBase+<GetServicesAsync>d__27.MoveNext ()(filename unknown)
       at Plugin.BLE.Abstractions.DeviceBase+<GetServiceAsync>d__28.MoveNext ()(filename unknown)

## Configuration

**Version of the Plugin:** 1.3.0

**Platform:** Android 9.0

**Device:** Motorola Moto G6

**Comment by smsissuechecker** [comment]
Hi @tqngan1984,

I'm the friendly issue checker.
It seems like (37.50 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by PawelGasiorowski** [comment]
I have the same problem. Anyone can help?
1. I connect to the device (pairing enabled)
2. I immediately get Connection Lost event
3. I can't get services - I get disconnected while fetching services error but it is only a result of a problem that is causing the connection losse.

**Comment by MarcAlx** [comment]
Confirm this is an issue, it also happens to me (not only on Android 9.0 but also on 7.0).

My step to repoduce : 

1. connect to device
2. Unplug device
3. try to access device

in my case the connection lost event hasn't been fired (while on iOS it is). 
What's blocking to me it's that the exception thrown can't be catch, leading to an app crash.

**Comment by xabre** [comment]
Feel free to reopen if this is still an issue in v2.0.1.
