### ISSUE TITLE
IBluetoothLE' is defined in an assembly that is not referenced (after fixing Strong-Named assembly)?

### ISSUE THREAD

**Issue by jvhgamer** [xabre/xamarin-bluetooth-le#355]
## Steps to reproduce

1. Create Windows Application project using Target Framework 4.5.1.

2. Add Plugin.BLE (used NuGet)

3. Run

4. Returns, "Could not load file or assembly 'Plugin.BLE.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)"

5. Download Plugin.BLE source and sign the Plugin.BLE.Abstractions project.
(By using the Signing tab in a project's Properties dialog box in Visual Studio.)

6. Use new Plugin.BLE.Abstractions assembly that has a strong-name.

7. Now returns, error CS0012: The type 'IBluetoothLE' is defined in an assembly that is not referenced. You must add a reference to assembly 'Plugin.BLE.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

## Configuration

**Version of the Plugin:** 2.0.0-pre1

**Platform:** Windows 10

**Device:** PC

**Comment by smsissuechecker** [comment]
Hi @jvhgamer,

I'm the friendly issue checker.
It seems like (37.50 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!
