### ISSUE TITLE
Android: Human readable error message if BLE is not supported on the platform (Emulator or version < 4.4KitKat)

### ISSUE THREAD

**Issue by allbdeveloper** [xabre/xamarin-bluetooth-le#36]
Hi, Very Thanks for this package.

Are you planning to support for KitKat or Jelly Bean.
It's crash on those version.

**Comment by smstuebe** [comment]
Where does it crash? Do you have a crash log and the code that causes the crash log? On which device are you testing?

**Comment by smstuebe** [comment]
More than one month no answer -> close

**Comment by allbdeveloper** [comment]
Hi, I’m so sorry that I reply so late.
I know you have put big effort to make library. 

So sorry again. 

BLE Adapter crash on Jellybean and Kitkat. (Both are tested on Xamarin Android Player - not actual device)



- JellyBean





- kitkat






Thanks.

**Comment by smstuebe** [comment]
Ok. We have to review that. Have you tested it on physical devices, too?

**Comment by allbdeveloper** [comment]
Hi, Thanks for reopening issue. 

Not yet. 

I will try it asap and send the result to you.

Thanks.

**Comment by smstuebe** [comment]
And: You say it's crashing. Please provide the exception messages and the stacktrace.

**Comment by allbdeveloper** [comment]
Hi, I attached screenshot with crash log. but it's not shown here. (I attached it using email)
DId you see that screenshot from email box? and you want more information? (exception messages & stacktrace) 
If so, I will send it.

Plus, It may take little longer to find actual device (Kitkat and Jellybean)

**Comment by allbdeveloper** [comment]
<Jelly Bean>
![screen shot 2016-05-12 at 2 20 26 pm](https://cloud.githubusercontent.com/assets/14910356/16128621/632da24c-343c-11e6-8d73-55fe784dd6f7.png)
![screen shot 2016-05-27 at 12 02 51 am](https://cloud.githubusercontent.com/assets/14910356/16128647/7ff0e650-343c-11e6-80cb-60c18e509d8d.png)
![screen shot 2016-05-27 at 12 02 59 am](https://cloud.githubusercontent.com/assets/14910356/16128651/84fd3662-343c-11e6-91cc-4c8ec09363ba.png)


<Kit Kat>
![screen shot 2016-05-27 at 12 04 24 am](https://cloud.githubusercontent.com/assets/14910356/16128659/8ea9a6d2-343c-11e6-86a5-628463b4ab30.png)
![screen shot 2016-05-27 at 12 12 25 am](https://cloud.githubusercontent.com/assets/14910356/16128666/99bfd12c-343c-11e6-9768-cc758fbe7931.png)

**Comment by allbdeveloper** [comment]
I tested it on actual device. 

Samsung Galaxy Note 1. (SHV-E160L)
It crash on this device. 

![screen shot 2016-06-17 at 11 34 02 pm](https://cloud.githubusercontent.com/assets/14910356/16154111/595bfda6-34e4-11e6-8741-bef1cc02a445.png)
![screen shot 2016-06-17 at 11 34 13 pm](https://cloud.githubusercontent.com/assets/14910356/16154114/5eb887e2-34e4-11e6-8acd-6dea876b98ce.png)
![screen shot 2016-06-17 at 11 33 50 pm](https://cloud.githubusercontent.com/assets/14910356/16154120/649eb50a-34e4-11e6-9195-7338dd4fbc1b.png)
![screen shot 2016-06-17 at 11 34 43 pm](https://cloud.githubusercontent.com/assets/14910356/16154125/6b41881a-34e4-11e6-9f4c-acd957af7694.png)

**Comment by allbdeveloper** [comment]
Hi, 

I tested it today on actual device (Galaxy Note 1)
Android 4.1.2 - Jelly Bean.

It crash. 

And I uploaded screenshots on github’s issue.

Thanks.

**Comment by allbdeveloper** [comment]
Oh, I found it from wikipedia .
https://en.wikipedia.org/wiki/Bluetooth_low_energy#Android

BLE's supported from Android 4.3 JellyBean or above.
So It shouldn't work on 4.1 JellyBean.

**Comment by xabre** [comment]
Android - Check BLE availability by:
- [ ] Checking SDK level and notify via log message
- [ ] Check if Emulator and notify via log message

**Comment by smstuebe** [comment]
We should try do not check if it's a simulator/emulator. Instead we should just check if ble is available.

**Comment by xabre** [comment]
You should not instantiate the Adapter by calling new. 

- If you use the vanilla version (non mvvmcross) of the plugin please resolve IAdapter by calling `CrossBluetoothLE.Current.Adapter `
- For MvvmCross use Mvx.Resolve<IAdapter>

For both cases, if** BLE it's not available on your device** you will get a fake adapter which will not crash and print out error messages.

You can always check availability by calling` CrossBluetoothLE.Current.IsAvailable`

For more info see our readme.

**Comment by allbdeveloper** [comment]
Thanks for your answer.
