### ISSUE TITLE
No AdvertisementRecords when connected to the known device

### ISSUE THREAD

**Issue by indutech** [xabre/xamarin-bluetooth-le#360]
The AdvertisementRecords are loaded when scanned for the device and then connected to the device. But if connected directly using "ConnectToKnownDeviceAsync", no AdvertisementRecords found. The count is zero, but the services are present.

## Steps to reproduce

1. Scan & Connect using:
   await adapter.StartScanningForDevicesAsync();
   await adapter.ConnectToDeviceAsync(d);
   Debug.WriteLine(d.AdvertisementRecords.Count);
  
   RESULT = 3

2. Connect directly to the device:
    d = await adapter.ConnectToKnownDeviceAsync(dDevGUID);
   Debug.WriteLine(d.AdvertisementRecords.Count);
  
   RESULT = 0

## Expected behavior
The record count should be same when the device is scanned & connected, or connected directly without scanning.

## Actual behavior
There are no records when connected directly to the KnownDevice

### Crashlog
No Crash

## Configuration

**Version of the Plugin:** e.g. 1.3.0

**Platform:** e.g. Android 8.0

**Device:** e.g. Google Pixel 3

**Comment by smsissuechecker** [comment]
Hi @indutech,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by xabre** [comment]
Current implementation: Advertisement records are only populated during scan. 

As far as I know, both for android and ios there is no way to get advertisement records without performing a scan (i.e. connecting to a known device directly). I would be glad if you could look into this more and perhaps prove me wrong.

Please reopen the issue if you find out anything.
