### ISSUE TITLE
Try to display characteristics on iphone

### ISSUE THREAD

**Issue by Toonyi** [xabre/xamarin-bluetooth-le#361]
Hi, I am new with xamarin and ble. I am trying to develop an app that connect with the nordic nrf51422 development kit which connected with a sensor. I am able to list the active ble and can connect the board with my iphone. And the next step I want to achieve is get two characteristics from the developement kit and display them on my iphone. and I have no idea how to achieve this. 

There are many written files in xabre's examaple and I  have no idea how to understand them and which file I should look at.

Can anybody tell me how to display the characteristics on my ios app or just tell me which files I should take a look?

Much appreciate!

**Comment by smsissuechecker** [comment]
Hi @Toonyi,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by xabre** [comment]
The sample app is your reference here. 

Take a look at:

- **ServiceListViewModel**: lists the available services of the connected device
- **CharacteristicListViewModel**: lists the characteristics of a selected service
- **CharacteristicDetailViewModel**: has functionality for reading / writing values for a characteristic as well as starting updates.

Will close this issues as it's more of a question. You may follow up here with additional queries.
