### ISSUE TITLE
CrossBluetoothLE class not found in Xamarin.Forms project

### ISSUE THREAD

**Issue by beeradmoore** [xabre/xamarin-bluetooth-le#367]
It seems that CrossBluetoothLE can't be used in a .netstandard project anymore, the class it not found in the namespace. The only namespace found in Plugin.BLE is Plugin.BLE.Abstractions. Possibly this isn't an error but the case on how to use Plugin.BLE has changed from how I was using it in the 1.3 release. I can see from the samples that IAdapter is passed around everywhere but I don't see where that reference comes from.

## Steps to reproduce

1. Create a new blank Xamarin.Forms application

2. Add Plugin.BLE Nuget package (as well as update all other nuget packages)

3. Try use Plugin.BLE.CrossBluetoothLE within the Xamarin.Forms project.

## Expected behavior
You can use the sample code of:
```
var ble = CrossBluetoothLE.Current;
var adapter = CrossBluetoothLE.Current.Adapter;
```

## Actual behavior
In the Xamarin.Forms project the CrossBluetoothLE class can not be found, even when referenced as Plugin.BLE.CrossBluetoothLE. However the Xamarin.iOS and Xamarin.Android projects can use that class fine.

Attached is a sample project which won't build due because the above reason.

[XFBLETest.zip](https://github.com/xabre/xamarin-bluetooth-le/files/3464664/XFBLETest.zip)

**Comment by smsissuechecker** [comment]
Hi @beeradmoore,

I'm the friendly issue checker.
It seems like (62.50 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by Tragetaschen** [comment]
The NuGet doesn't contain the Plugin.BLE.dll anymore
![image](https://user-images.githubusercontent.com/1947968/62426688-58ccde80-b6e8-11e9-8a87-3cbc44ba4c28.png)

I have no real clue about the build tools, but isn't this
https://github.com/xabre/xamarin-bluetooth-le/blob/8a35f7bad8990cc5bb47c863bd9ba9ea15889802/.build/build.cake#L67-L69
essentially missing to build the project?
