### ISSUE TITLE
ConnectToKnownDeviceAsync Crashes App When Bluetooth is not in Range in Version 2.1.0 with iOS 12+

### ISSUE THREAD

**Issue by BlueFire-LLC** [xabre/xamarin-bluetooth-le#373]
To help us fix your issue, please provide the information in the below template. If something causes a crash, provide as much information as you can gather.
Just imagine: we do not know what you are doing! 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.

## Steps to reproduce

Hard to do as it's buried deep into my App

## Expected behavior
The App should not crash.

## Actual behavior
The App crashes.

### Crashlog

Not sure how to get this.

## Configuration

**Version of the Plugin:**  2.1.0 (2.0.1 works)

**Platform:** e.g. iOS 12+, 13

**Device:** e.g. iPad, iPhone

**Comment by smsissuechecker** [comment]
Hi @BlueFire-LLC,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by BlueFire-LLC** [comment]
Just discovered this and going back to 2.0.1 fixed the issue. Hard to provide a test case as it's buried deep into my App. No problem with Android, only iOS 12+. Ok with iOS 9+. Not sure about 10 or 11. Hopefully it is something easily fixed but let me know if I can provide anything else.

**Comment by xabre** [comment]
Should be fixed by release 2.1.1.

**Comment by BlueFire-LLC** [comment]
2.1.1 fixed it. Thanks.
