### ISSUE TITLE
Unable to Write and read in plugin BLE

### ISSUE THREAD

**Issue by suriyaKalidoss21** [xabre/xamarin-bluetooth-le#379]
I need to get the correct characteristic to read and write in Bluetooth device but among two characteristics, Unable to read the values from read characteristic. Correct me if I'm wrong in code

**Code:**
characteristic property type-->write/write response

characteristic property type-> indicate

            var services = await connectedDevice.GetServicesAsync();
            var serviceid = services[0].Id;
            var service = await connectedDevice.GetServiceAsync(serviceid);
            var characteristics = await service.GetCharacteristicsAsync();
            var characteristicread= await service.GetCharacteristicAsync(characteristics[1].Id);
            var characteristicWrite = await service.GetCharacteristicAsync(characteristics[0].Id);
            byte[] bytes = Encoding.ASCII.GetBytes("LIST_DIR,audio");
            await characteristicWrite.WriteAsync(bytes);
          
            characteristicread.ValueUpdated += (s, ee) =>
                {
                    var result = ee.Characteristic.Value;
                    var stre = System.Text.Encoding.UTF8.GetString(result, 0, result.Length);
                   //i can't able read charecterstic
                };
                await characteristicread.StartUpdatesAsync();
#
![image](https://user-images.githubusercontent.com/51110790/64471108-715a6980-d16a-11e9-808f-63b4491ad3a7.png)
# Steps to reproduce
1.copy the above code and run it in iOS device ble
2.unable to read characteristic after write

## Expected behavior
after write value in write characteristic value should be updated in read characteristic

## Actual behavior
read characteristic value not updated 

## Configuration

**Platform:** e.g. iOS 10.1 ,Xamarin.forms IOS

##Exception
Objective-C exception thrown. Name: NSInternalInconsistencyException Reason: Client Characteristic Configuration descriptors must be configured using setNotifyValue:forCharacteristic:
While read

**Comment by smsissuechecker** [comment]
Hi @suriyaKalidoss21,

I'm the friendly issue checker.
It seems like (50.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by suriyaKalidoss21** [comment]
i have edited the comment

**Comment by YBENZAKOUR** [comment]
@suriyaKalidoss21  Hello, please do you found the right method to learn and send message? I need it please 
Thank's
