### ISSUE TITLE
Unable to read after charecteresteric write

### ISSUE THREAD

**Issue by suriyaKalidoss21** [xabre/xamarin-bluetooth-le#383]
## Steps to Reproduce
1. In your GitHub sample, Write the bytes to write characteristic, Refer screenshot
        <img width="846" alt="Screenshot 2019-09-17 at 5 00 44 PM" src="https://user-images.githubusercontent.com/51110790/65039162-3aa50000-d96f-11e9-95d3-6b6272f84fd8.png">
        
![Skype_Picture_2019_09_17T11_46_46_561Z](https://user-images.githubusercontent.com/51110790/65039195-4db7d000-d96f-11e9-9361-55972ba9314f.jpeg)

2.Unable to read data after the write you can refer the screenshot
![Skype_Picture_2019_09_17T11_45_41_477Z](https://user-images.githubusercontent.com/51110790/65039292-88216d00-d96f-11e9-9e58-08ffd79e9ce2.jpeg)

3. In the above image you can see there is no read data updated after write

## Expected behavior
 Need to read after write

## Actual behavior
  I can't able to read after write
Characterestic image:
<img width="465" alt="Screenshot 2019-09-03 at 5 45 24 PM" src="https://user-images.githubusercontent.com/51110790/65115637-a639ac80-da05-11e9-97e8-ea159ee6a92b.png">

## Configuration

**Version of the Plugin:** 6.2.6

**Platform:** Xamarin.FOrms.IOS, Not test in Android

**Device:** IPHONE XS

**Comment by smsissuechecker** [comment]
Hi @suriyaKalidoss21,

I'm the friendly issue checker.
It seems like (25.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!
