### ISSUE TITLE
Android Crash when attempting call to ReadAsync() for a Characteristic.

### ISSUE THREAD

**Issue by JonathanWebsdale** [xabre/xamarin-bluetooth-le#386]
## Steps to reproduce

1. Connect to a known device with a call to 
                    var knownDevice = await adapter.ConnectToKnownDeviceAsync(device.Id, default(Plugin.BLE.Abstractions.ConnectParameters), this.cancellationToken.Token);

2. Get the device services
                    var services = await knownDevice?.GetServicesAsync();

3. Get the generic access service
                    var genericAccessService = services.FirstOrDefault(x => BleDeviceHelper.ConvertUuidToShortId(x.Id) == (ushort)GattNativeServiceUuid.GenericAccess);

4. Get the characteristic for Device Name
                    var characteristic = await genericAccessService.GetCharacteristicAsync(BleDeviceHelper.CreateUuidForCharacteristic(genericAccessService.Id, GattNativeCharacteristicUuid.DeviceName));

5. Read the characteristic
                        if(characteristic != null && characteristic?.CanRead == true)
                            var bytes = await characteristic.ReadAsync(this.cancellationToken.Token);

## Expected behavior
the value returned by ReadAsync should contain the value for the characteristic.

## Actual behavior
Application crashes in both debug and release configurations.

### Crashlog

09-25 11:00:49.735 D/BluetoothGatt( 6796): onSearchComplete() = Device=60:64:05:CD:98:D5 Status=0
09-25 11:00:49.735 D/BluetoothDevice( 6796): mAddress: 60:64:05:CD:98:D5
09-25 11:00:49.763 D/BluetoothDevice( 6796): mAddress: 60:64:05:CD:98:D5
09-25 11:00:49.763 D/BluetoothDevice( 6796): mAddress: 60:64:05:CD:98:D5
09-25 11:00:49.763 D/BluetoothDevice( 6796): mAddress: 60:64:05:CD:98:D5
09-25 11:00:49.763 D/BluetoothDevice( 6796): mAddress: 60:64:05:CD:98:D5
09-25 11:00:54.158 D/BluetoothGatt( 6796): readCharacteristic() - uuid: 00002a00-0000-1000-8000-00805f9b34fb
09-25 11:00:54.158 D/BluetoothDevice( 6796): mAddress: 60:64:05:CD:98:D5
09-25 11:00:54.312 D/BluetoothGatt( 6796): onCharacteristicRead() - Device=60:64:05:CD:98:D5 UUID=00002a00-0000-1000-8000-00805f9b34fb Status=0 srvcType=0 srvcInstId=0 charInstId=0
09-25 11:00:54.312 D/BluetoothDevice( 6796): mAddress: 60:64:05:CD:98:D5
09-25 11:00:54.312 D/BluetoothDevice( 6796): mAddress: 60:64:05:CD:98:D5
Thread started:  #15
09-25 11:00:57.027 F/        ( 6796): * Assertion at /Users/builder/jenkins/workspace/xamarin-android-d15-9/xamarin-android/external/mono/mono/mini/debugger-agent.c:4931, condition `is_ok (error)' not met, function:get_this_async_id, Could not execute the method because the containing type is not fully instantiated. assembly:<unknown assembly> type:<unknown type> member:(null)
09-25 11:00:57.027 F/libc    ( 6796): Fatal signal 6 (SIGABRT), code -6 in tid 6796 (m.l2s2.Reassure)

## Configuration

**Version of the Plugin:** 2.1.1

**Platform:** e.g. Android 6.0

**Device:** e.g. Blackview A8 MAX

**Comment by smsissuechecker** [comment]
Hi @JonathanWebsdale,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by JonathanWebsdale** [comment]
Issue turned out to be issue with calling XMLSerialization on the data saving the list of devices, but Android debugger not giving an exception at the Xamarin level, Sorry for raising issue.
