### ISSUE TITLE
Plugin.BLE crashes app on iPad iOS 13.1

### ISSUE THREAD

**Issue by mspoehr** [xabre/xamarin-bluetooth-le#387]
To help us fix your issue, please provide the information in the below template. If something causes a crash, provide as much information as you can gather.
Just imagine: we do not know what you are doing! 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.

## Steps to reproduce

1. Reference `CrossBluetoothLE.Current` in any capacity

2. Deploy app to iOS running iOS 13

This occurs with a fresh Xamarin.Forms app built with a single button which runs the following code when clicked:

```cs
bool bleEnabled = CrossBluetoothLE.Current.State == BluetoothState.On
```

It also occurs with the sample application provided in this repository. 

## Expected behavior

Code should execute normally without crashing. 

## Actual behavior

App crashes immediately.

### Crashlog

This error appears to happen in native code an no stack trace shows up in the log.

## Configuration

**Version of the Plugin:** 2.1.1 (also doesn't work on earlier versions)

**Platform:** iOS 13

**Device:** iPad 9.7 inch (5th generation)

**Comment by smsissuechecker** [comment]
Hi @mspoehr,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by mspoehr** [comment]
I needed to add both NSBluetoothAlwaysUsageDescription and NSBluetoothPeripheralUsageDescription to my info.plist per https://developer.apple.com/documentation/bundleresources/information_property_list/nsbluetoothalwaysusagedescription since our deployment target is < iOS 13.

Everything is working now, but this information should likely be added to the readme so future people don't get hung up on the same issue.

**Comment by dannythunder** [comment]
Thanks for this @mspoehr

**Comment by xabre** [comment]
Readme was updated thanks to @smstuebe. Will close this issue.
