### ISSUE TITLE
[Android] No Pairing Dialog shown in Xamarin Forms

### ISSUE THREAD

**Issue by hendriksandberg** [xabre/xamarin-bluetooth-le#392]
Hello,
first of all sorry for my bad english.
I hope i can explain the Problem as detailed as much without many informations.
We use this plugin to communicate with a custom bluetooth le device. After we try to establish a connection with the device we expect to get a dialog to pair the devices but do not get one.
Our mainproject is in Xamarin.Forms 4.3, we also tested it with the given testproject in Xamarin.Forms 4.2 and get the same behavior.

Maybe there is a know issue or some tips to get more information out of the connection process.

## Steps to reproduce

1. Download Test-Project (Xamarin Forms)

2. Start on Android-Device

## Expected behavior
After the connection is established a Pairing Dialog should Pop up.
You should then insert ther pairing code from the other device and accept.

## Actual behavior
The connection is successfully established but no pairing dialog was shown.

### Crashlog

Atm no Error or Crash log 

## Configuration

**Version of the Plugin:** Testproject from actual Master Branch

**Platform:** Android 10, Android 9 (Xamarin Forms 4.2)

**Device:** Pixel 3 XL, OnePlus 5T

**Comment by smsissuechecker** [comment]
Hi @hendriksandberg,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by hendriksandberg** [comment]
Hi,
we managed to get to pairing dialog.
We had to choose a specific characteristic out of the connected device and then starts listening on a service.
After a few moments the pairing dialog will popup if the devices isnt paired already.
