### ISSUE TITLE
Is Plugin.BLE v 1.3.0 compatible with iOS 13?

### ISSUE THREAD

**Issue by walhallaOPS** [xabre/xamarin-bluetooth-le#393]

**Comment by smsissuechecker** [comment]
Hi @walhallaOPS,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!
