### ISSUE TITLE
Continue the second communication after the first communication is completed and cannot get a reply.

### ISSUE THREAD

**Issue by LinuxAndOracle** [xabre/xamarin-bluetooth-le#395]
Sorry to bother you. I have a problem that is difficult to solve. After writing the data for the first time and getting a reply, I made a second write. Then I didn't receive any reply. I can only get a second reply if I close the project and then I can't get a reply after the third write. I don't know what the reason is, I hope to get your help.

## Steps to reproduce

1.Bluetooth scanning

2.Binding characteristic For Write And Read

3.

## Expected behavior
When I write data for the second time or even a few times, I can get a reply.

## Actual behavior
I only get the reply for the first time.

## Configuration

**Version of the Plugin:** 2.1.1

**Platform:** Android 8.0 

**Device:** XiaoMi MI 6

**Comment by smsissuechecker** [comment]
Hi @LinuxAndOracle,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.
