### ISSUE TITLE
Should this work in UWP or not?

### ISSUE THREAD

**Issue by JerryNixon** [xabre/xamarin-bluetooth-le#399]
Thank you for this library.

We're having issues and before we chase them, it's just not clear: Should it work?

**Comment by smsissuechecker** [comment]
Hi @JerryNixon,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by xabre** [comment]
The latest pre release includes the uwp verison (2.2.0-pre.*)
