### ISSUE TITLE
Adapter.StartScanningForDevicesAsync() crashed on iOS 13.3

### ISSUE THREAD

**Issue by janlange** [xabre/xamarin-bluetooth-le#405]
This simple code makes the iOS Xamarin app crash on iOS 13.3, it worked fine on iOS 12.x

adapter = CrossBluetoothLE.Current.Adapter;

// THIS LINE MAKES THE APP CRASH:
await adapter.StartScanningForDevicesAsync();

foreach (IDevice idev in adapter.DiscoveredDevices)
...

Plugin 2.2.0-pre2
iOS 13.3 
IPhone 10 XS MAX

**Comment by smsissuechecker** [comment]
Hi @janlange,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by Tacomatt** [comment]
I just updated my iPhone XS to 13.3.1 Public Beta 2 and am seeing the same behavior. It did the same thing when I was on Public Beta 1 as well as with the official 13.3 release on an iPhone 8.

**Comment by janlange** [comment]
I found the answer in the updated readme:
Add these to info.plist:
<key>NSBluetoothAlwaysUsageDescription</key>
<string>YOUR CUSTOM MESSAGE</string>
