### ISSUE TITLE
Hi, this is more a a question than an issue

### ISSUE THREAD

**Issue by abreucruz** [xabre/xamarin-bluetooth-le#408]
I'm trying to print to a Bluetooth thermal printer using your plugin, I was able to connect to the printer but I would like to know how can I send an string directly to the bluetooth printer socket in IOS?

**Comment by smsissuechecker** [comment]
Hi @abreucruz,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by MKuckert** [comment]
There is no simple answer to this question. You have to know the devices API to interact with its services and characteristics. You'd like to have a deeper look into the BLE GATT profile.

**Comment by abreucruz** [comment]
Thanks Martin,

I was able to solved it saving the characters as image file and print the information as image instead of plain texts.
