### ISSUE TITLE
StartScanningForDevicesAsync not working

### ISSUE THREAD

**Issue by georgemichailou** [xabre/xamarin-bluetooth-le#419]
The StartScanningForDevicesAsync method is not find devices.

https://github.com/georgemichailou/working-with-plugins

## Steps to reproduce

1. Following the documentation (vanilla package)

2. Scan for devices 

## Expected behavior
Find available Devices 

## Actual behavior
Nothing happened. I get every time timeout without any result. I increase and the timeout value without success.

## Configuration

**Version of the Plugin:** 2.2.0-pre2 and 2.2.1

**Platform:** Android 9 

**Device:** Samsung s8

**Comment by georgemichailou** [comment]
The Plugin.BLE.Abstractions.Contracts.ScanMode.LowLatency fixing the problem. Thank you

**Comment by bbenetskyy** [comment]
We have just the same problem and ScanMode LowLatency does not fix the problem for us. I will back here when we will find a solution.

**Comment by naveenchaganti** [comment]
StartScanningForDevicesAsync is not working even ScanMode LowLatency mode.

**Comment by Denaindra** [comment]
@naveenchaganti  have you fixed your issue , me also facing same issue ?
