### ISSUE TITLE
Is this plugin supports for Visual studio 2019 Xamarin Projects

### ISSUE THREAD

**Issue by ShaileshBhatNP** [xabre/xamarin-bluetooth-le#437]
Is this plugin supports for Visual studio 2019 Xamarin Projects?

Hi, I need to build an Xamarin app using VS2019 and this plugin. Is it possible?. I was confused, after searching for a day..If yes, Can I get the sample in VS2019..I have tried with many samples, but no one is supporting/running in VS2019

**Comment by smsissuechecker** [comment]
Hi @ShaileshBhatNP,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by ShaileshBhatNP** [comment]
Where is the template..can you please send me the link..?

**Comment by ShaileshBhatNP** [comment]
https://github.com/didourebai/BLEPluginDemo

Got above template which used this plugin..But Failing to Connect

**Comment by xabre** [comment]
Please check out the soruce code and run the Sample project. Everything should be fine with VS2019. 

For your own project follow the insturctions in the readme and install the nuget package to all platform specific csprojects and also you shared core csproj.

**Comment by ShaileshBhatNP** [comment]
Ok. Thank you, we have to open Source folder for getting sample project(after cloning outer folder)..
