### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by coffice12** [xabre/xamarin-bluetooth-le#444]
=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x1984d57f4):0x1984d57e4  c0 03 5f d6 c0 03 5f d6 30 41 80 d2 01 10 00 d4  .._..._.0A......
0x1984d57f4  e3 00 00 54 fd 7b bf a9 fd 03 00 91 b4 80 ff 97  ...T.{..........
0x1984d5804  bf 03 00 91 fd 7b c1 a8 c0 03 5f d6 c0 03 5f d6  .....{...._..._.
0x1984d5814  d0 03 80 d2 01 10 00 d4 e3 00 00 54 fd 7b bf a9  ...........T.{..

**Comment by smsissuechecker** [comment]
Hi @coffice12,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by coffice12** [comment]
ios 13.5
