### ISSUE TITLE
Set name for devices returning as null

### ISSUE THREAD

**Issue by ACSdesignservices** [xabre/xamarin-bluetooth-le#449]
To help us fix your issue, please provide the information in the below template. If something causes a crash, provide as much information as you can gather.
Just imagine: we do not know what you are doing! 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.

## Steps to reproduce

1. Please see Expected behavior below

2.

3.

## Expected behavior
Hello - the plugin is working correctly. Since some BLE devices return null for their device name. Is it possible to set their name to something other than null - i.e. no name or something like that? If this has already been answered I apologize.

BTW - thank you for this plugin - very helpful!!

## Actual behavior
Tell us what happens instead

### Crashlog
NONE

## Configuration

**Version of the Plugin:** e.g. 1.0.0 / 1.0.1-alpha3
Plugin.BLE version 2.1.1

**Platform:** e.g. iOS 10.1 / Android 4.4 / ... (including version!!! e.g. Android 5.1 / i0S 10)
IOS - 13.6

**Device:** e.g. HTC Sensation /i Phone 7 ...
iPhone 7

**Comment by smsissuechecker** [comment]
Hi @ACSdesignservices,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.
