### ISSUE TITLE
How to Read / Write with PluginBLE Xamarin 

### ISSUE THREAD

**Issue by nowlights** [xabre/xamarin-bluetooth-le#451]
Good night!

I am developing an Xamarin.Forms application for bluetooth connection with an external device ... The application can now display the available devices and make the connection, when looking for services I have the following

[0] Generic Access

[1] Generic Attribute

[2] Device Information

[3] TI SensorTag Smart Keys

I use [1] that would be the GATT (Generic Attribute Profile) where I send and receive information with the device, correct?

Each service has characteristics, this one specifically has only 1, where it is CanRead = false and CanWrite = false ... if I try to do a .Read (), it generates a null error

**Comment by smsissuechecker** [comment]
Hi @nowlights,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by nowlights** [comment]
c
