### ISSUE TITLE
Scanning doesn't find any devices

### ISSUE THREAD

**Issue by rafaelagp** [xabre/xamarin-bluetooth-le#453]
Scanning works fine when compiling with SDK 28 but fails to find devices with any SDK upwards when running on Android 10.

## Steps to Reproduce
1. Call StartScanningForDevicesAsync()
2. DeviceDiscovered is never called
3.

## Expected behavior
Callback DeviceDiscovered is run whenever a device is found after calling StartScanningForDevicesAsync().

## Actual behavior
StartScanningForDevicesAsync() discovers no device.

**Crashlog:**
No exception is thrown.

## Configuration

**Version of the Plugin:** 2.1.1 and 2.2.0-pre2
**Platform:** Android 10
**Device:** Samsung Galaxy S10 and Google Pixel
**Android Target SDK**: 29+

**Comment by smsissuechecker** [comment]
Hi @rafaelagp,

I'm the friendly issue checker.
It seems like (25.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!
