### ISSUE TITLE
Scanning doesn't see any devices

### ISSUE THREAD

**Issue by rafaelagp** [xabre/xamarin-bluetooth-le#454]
Scanning works fine when compiling with SDK 28 but fails to find devices with any SDK upwards when running on Android 10.

## Steps to reproduce

1. Call StartScanningForDevicesAsync()

2. DeviceDiscovered is never called

3.

## Expected behavior
Callback DeviceDiscovered is run whenever a device is found after calling StartScanningForDevicesAsync().

## Actual behavior
StartScanningForDevicesAsync() discovers no device.

### Crashlog

No exception is thrown.

## Configuration

**Version of the Plugin:** 2.1.1 and 2.2.0-pre2

**Platform:** Android 10

**Device:** Samsung Galaxy S10 and Google Pixel

**Android Target SDK**: 29+

**Comment by smsissuechecker** [comment]
Hi @rafaelagp,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by travistodd099** [comment]
I am seeing the same.

**Comment by samosim** [comment]
I have the same problem.

**Comment by rafaelagp** [comment]
Solved it.

As of Android 6.0 Marshmallow, ACCESS_FINE_LOCATION permission is needed instead of ACCESS_COARSE_LOCATION for BLE functionality. Well, it isn't exactly needed, but for supporting all Android versions it is best.
