### ISSUE TITLE
Android 9 or higher don't starUpdateAsync

### ISSUE THREAD

**Issue by kvrscream** [xabre/xamarin-bluetooth-le#459]
Hello.  And sorry, my English is not good.  I'm trying to run StartUpdateAsync to notify the device and release a next measurement.
In android version 8 or lower it works and runs the command without problems. The same goes for the iPhone. But for any android version 9 or higher it just ignores the code.
How should I proceed

## Steps to reproduce
1. Connect to the BLE Device 
2. Try  StartUpdateAsync  
## Expected behavior
Update on indicate device.
## Actual behavior
Skip rest code and stop get device info.
## Crashlog
[BluetoothGatt] setCharacteristicNotification() - uuid: 00002a1c-0000-1000-8000-00805f9b34fb enable: true
[Mono] DllImport searching in: '__Internal' ('(null)').
[Mono] Searching for 'java_interop_jnienv_new_byte_array'.
[Mono] Probing 'java_interop_jnienv_new_byte_array'.
[Mono] Found as 'java_interop_jnienv_new_byte_array'.
[Mono] DllImport searching in: '__Internal' ('(null)').
[Mono] Searching for 'java_interop_jnienv_set_byte_array_region'.
[Mono] Probing 'java_interop_jnienv_set_byte_array_region'.
[Mono] Found as 'java_interop_jnienv_set_byte_array_region'.
[ViewRootImpl@c75a8a1[MainActivity]] ViewPostIme pointer 0
[inos.mais_amig] Compiler allocated 4266KB to compile void android.view.ViewRootImpl.performTraversals()
## Configuration
Version of the Plugin: 2.1.1
Platform: Android 10.0 API 29
Device: Samsung A20, Moto G7

**Comment by smsissuechecker** [comment]
Hi @kvrscream,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by kvrscream** [comment]
@smsissuechecker  Sorry. I edited for you're.

**Comment by ske66** [comment]
That doesn't look like a very useful Crashlog. Can you share a code example as well as output/exceptions?

**Comment by kvrscream** [comment]
Hi @ske66 
Look my code here:

`if (device != null)
                {

                    await adapter.StopScanningForDevicesAsync();
                    await adapter.DisconnectDeviceAsync(device);
                    await adapter.ConnectToDeviceAsync(device);

                    var services = await device.GetServicesAsync();

                    ICharacteristic characteristicTemperature = null;
                    ICharacteristic characteristicBattery = null;

                    foreach (var service in services)
                    {
                        var caracteristicas = await service.GetCharacteristicsAsync();


                        foreach (var carac in caracteristicas)
                        {
                            //Bug android 9 ou > -- Problemas ao notificar o device
                            //Checa se é Bateria ou Temperatura
                            if (carac.Uuid == "2a19" || carac.Uuid == "2a1c"
                                || carac.Name.ToLower().Equals("temperature measurement")
                                || carac.Name.ToLower().Equals("battery level"))
                            {

                                if(carac.Name.ToLower().Equals("battery level") || carac.Uuid == "2a19")
                                {
                                    characteristicBattery = carac;
                                }

                                if(carac.Name.ToLower().Equals("temperature measurement") || carac.Uuid == "2a1c")
                                {
                                    characteristicTemperature = carac;
                                }

                            }
                        }
                    }


                   
                        characteristicTemperature.ValueUpdated += (o, args) =>
                        {
                            byte[] bytes = args.Characteristic.Value;
                        };
                        
                        await characteristicTemperature.StartUpdatesAsync();

                    `

**Comment by kvrscream** [comment]
Hi everyone. I found the solution \o/

The problem is on Android device. I reseted my bluetooth and network setting and my Android device and now startUpdateAsync normaly.

Thanks all for help me.
