### ISSUE TITLE
Sample app

### ISSUE THREAD

**Issue by nitinjs** [xabre/xamarin-bluetooth-le#460]
do you have sample app to demonstrate ability of the library?

**Comment by smsissuechecker** [comment]
Hi @nitinjs,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by ske66** [comment]
Yes

https://github.com/xabre/xamarin-bluetooth-le/tree/master/Source/BLE.Client

Please read all of the Read Me
