### ISSUE TITLE
Android does not display avaiable devices and connected devices.

### ISSUE THREAD

**Issue by Denaindra** [xabre/xamarin-bluetooth-le#466]
## Steps to reproduce

1. Install latest Bluetooth -le NuGet package

2. Implement the code 

3. Enble blutooth all devices and Run the application 

## Sample code 

                var state = ble.State;
                adapter.ScanMode = ScanMode.LowLatency;
                adapter.ScanTimeout = 20000;

                if (!ble.Adapter.IsScanning)
                {
                    await adapter.StartScanningForDevicesAsync();

                }

                adapter.DeviceDiscovered += (s, a) =>
                {
                    Devices.Add(a.Device);
                };

                var list = adapter.ConnectedDevices;

	<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
	<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
	<uses-permission android:name="android.permission.BLUETOOTH" />
	<uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
        <uses-feature android:name="android.hardware.bluetooth_le" android:required="true"/>

## Actual behavior
not displaying any available devices and connected devices when bluetooth opend

## Configuration

**Version of the Plugin:** Plugin.BLE 2.1.1

**Platform:**  Android 10

**Device:** Redmi...

**Version of the Xamarin form:** 4.8.0.1451

**Comment by smsissuechecker** [comment]
Hi @Denaindra,

I'm the friendly issue checker.
It seems like (25.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by Denaindra** [comment]
This sort, you have to request location permission
