### ISSUE TITLE
Adapter.DiscoveredDevices is always zero in Vanilla version

### ISSUE THREAD

**Issue by Jockey4her** [xabre/xamarin-bluetooth-le#467]
I am trying to make a Vanilla version using your Mvx version as a guide.
I was able to get the MVX sample working fine, but so far not a vanilla.  I get a reference to the Adapter in MainPage.xaml.cs
            BLEInstance = CrossBluetoothLE.Current;
            Adapter = BLEInstance.Adapter;
            BLEInstance.Adapter.DeviceDiscovered += OnDeviceDiscovered;

and used the
            Adapter.ScanMode = ScanMode.LowLatency;
            await Adapter.StartScanningForDevicesAsync();
to start it off.  But I get no discovered devices. In the Mvx origina, I see at least 8 devices around.
I can see it scanning=true, so something is functioning. And it times out. But no results.

Q: In your Mvx sample, you include all the Plugin.BLE.xxx locally and add them to the project rather than get the Nuget Plugin.BLE.  Is that correct?  

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.
https://github.com/Jockey4her/Chief
I made a blank project, included the nuget BLE.Plugin 2.1.1. and some simple code to start it scanning. My device has BT enabled.

## Steps to reproduce

1. Use a Vanilla version to start a scan from a blank MainPage.xaml.cs.  Not seeing DiscoveredDevices even though Adapter says it is scanning.

2.

3.

## Expected behavior
The Mvx version sees at least 8 devices very quickly. But I get none in my attempt at a vanilla.  I wish you could publish a vanilla version; it is very hard to try and understand what to do when MvvmCross.Plugin.BLE is there.  You dont know what's missing.

## Actual behavior
OnCeviceDiscovered never fires. 
### Crashlog

If something causes an exception paste full stack trace + Exception here

## Configuration

**Version of the Plugin:** e.g. 1.0.0 / 1.0.1-alpha3
Plugin 2.1.1 - stored locally from the Mvx sample of bluetoothLe, not the Nuget version.
**Platform:** e.g. iOS 10.1 / Android 4.4 / ... (including version!!! e.g. Android 5.1 / i0S 10)
Android target version 9.0 (Pie).  
**Device:** e.g. HTC Sensation /i Phone 7 ...
Galaxy S9

**Comment by smsissuechecker** [comment]
Hi @Jockey4her,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by Jockey4her** [comment]
ah yes!  Gosh I love it when things are simple.. 
OK.. if this happens to you, don't panic. What it was was that you have to go into Settings on droid, and App info, Permissions, and MANUALLY enable Location permission.. Even though you set Permissions in the AppManifest, and you'd think it would popup something it doesn't.. Without it, the Adapter scans, but you get no results.  Fixed!    Thanks xabre.  and also to msthrax because I didn't catch the issue until I tried his version.    Vanilla fudge awaits.
