### ISSUE TITLE
Are there plans to add support for canSendWriteWithoutResponse on iOS11+ ?

### ISSUE THREAD

**Issue by kwintAl** [xabre/xamarin-bluetooth-le#473]
On iOS devices, it's currently not possible to send a large amount of data to the peripheral device (without response).

On iOS11+ there is a property that indicates the current state: [canSendWriteWithoutResponse](https://developer.apple.com/documentation/corebluetooth/cbperipheral/2891512-cansendwritewithoutresponse?language=objc) and [peripheralIsReadyToSendWriteWithoutResponse](https://developer.apple.com/documentation/corebluetooth/cbperipheraldelegate/2874034-peripheralisreadytosendwritewith?language=objc)

So in case canSendWriteWithoutResponse returns false, we should wait until the peripheralIsReadyToSendWriteWithoutResponse is called.

## Steps to reproduce

1. Connect to peripheral device

2. Send a large amount of data (without response)

## Expected behavior
no data loss

## Actual behavior
data loss

## Configuration

**Version of the Plugin:** e.g. 2.1.0

**Platform:**  iOS 14 / 13

**Device:** iPhone 11 / iPhone 6

**Comment by smsissuechecker** [comment]
Hi @kwintAl,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by geri-m** [comment]
The place where this check needs to be implemented is https://github.com/xabre/xamarin-bluetooth-le/blob/master/Source/Plugin.BLE.iOS/Characteristic.cs#L159. Currently the write would return immediately and the event from `peripheralIsReadyToSendWriteWithoutResponse` is not considered.

**Comment by janusw** [comment]
Fixed with #554.
