### ISSUE TITLE
Clear cached services after disconnect. 

### ISSUE THREAD

**Issue by smstuebe** [xabre/xamarin-bluetooth-le#48]
Pulled the bug out from issue #47 so we can handle feature request and bug separately

from @domo4all:

Also, I noticed that if I disconnect from a device, than I can connect again to that device but cannot exchange any data. I have to perform a discovery before to make it work again.
Do I make something wrong?

from @xabre:
I think I know what the problem is. We do not clear the list of KnownServices on disconnect, and when reusing the instance of the IDevice it uses the list of cached services from the previous connection.

Yes, there is no call to discover services after the second connection
[BluetoothGatt] discoverServices() - device: 20:91:48:BB:C8:9A
We will publish a fix for this problem. Maybe later today -beta4. Thank you for pointing it out.

**Comment by xabre** [comment]
@domo4all We have just released 1.0.0-beta4 which should include the fix for this issue.

**Comment by domo4all** [comment]
@xabre Thank you. I tried it and it works perfectly. Really nice job :)
