### ISSUE TITLE
Android: Connection attempts fail with MAX client reached: 32

### ISSUE THREAD

**Issue by MKuckert** [xabre/xamarin-bluetooth-le#484]
Continuously attempting to connect to a known device on android for a longer time period (after 32 attempts) leaves the system in a state that totally blocks the current applications BLE activity. One can see the following logs in LOGCAT:

For a successful attempt:

```
D/BluetoothGatt( 8606): connect() - device: 00:12:6F:5D:F1:B5, auto: true
D/BluetoothGatt( 8606): registerApp()
D/BluetoothGatt( 8606): registerApp() - UUID=9f59b502-b6a5-407a-a58f-d88948d83d46
I/bt_stack( 5197): [INFO:gatt_api.cc(946)] GATT_Register 08141223-f502-8790-5e97-d36a63acaf5c
I/bt_stack( 5197): [INFO:gatt_api.cc(966)] allocated gatt_if=7
D/BluetoothGatt( 8606): onClientRegistered() - status=0 clientIf=7
D/bt_btif_config( 5197): btif_get_address_type: Device [00:12:6f:5d:f1:b5] address type 0
D/bt_btif_config( 5197): btif_get_device_type: Device [00:12:6f:5d:f1:b5] type 2
I/bt_stack( 5197): [INFO:gatt_api.cc(1104)] GATT_Connectgatt_if=7, address=00:12:6f:5d:f1:b5
D/BluetoothGatt( 8606): cancelOpen() - device: 00:12:6F:5D:F1:B5
E/bt_stack( 5197): [ERROR:bta_gattc_act.cc(293)] No such connection need to be cancelled
I/bt_stack( 5197): [INFO:gatt_api.cc(1163)] GATT_CancelConnect: gatt_if:7, address: 00:12:6f:5d:f1:b5, direct:0
D/BluetoothGatt( 8606): close()
D/BluetoothGatt( 8606): unregisterApp() - mClientIf=7
```

For a failing attempt:

```
D/BluetoothGatt( 2527): connect() - device: 00:12:6F:5D:F1:B5, auto: true
D/BluetoothGatt( 2527): registerApp()
D/BluetoothGatt( 2527): registerApp() - UUID=f5ac3a2e-601a-4899-a444-53f8c90a2dfb
I/bt_stack(29157): [INFO:gatt_api.cc(946)] GATT_Register 3164730b-c133-3a26-dd94-4ae52f81670d
E/bt_stack(29157): [ERROR:gatt_api.cc(971)] can't Register GATT client, MAX client reached: 32
E/bt_stack(29157): [ERROR:bta_gattc_act.cc(185)] Register with GATT stack failed.
I/bt_stack(29157): [INFO:gatt_api.cc(946)] GATT_Register 3164730b-c133-3a26-dd94-4ae52f81670d
E/bt_stack(29157): [ERROR:gatt_api.cc(971)] can't Register GATT client, MAX client reached: 32
E/bt_stack(29157): [ERROR:bta_gattc_act.cc(185)] Register with GATT stack failed.
D/BluetoothGatt( 2527): onClientRegistered() - status=133 clientIf=0
D/BluetoothGatt( 2527): close()
D/BluetoothGatt( 2527): unregisterApp() - mClientIf=0
```

Especially the entries stating `can't Register GATT client, MAX client reached: 32 […] Register with GATT stack failed.` are worrying. One can also observe that the `allocated gatt_if=7` count increases with each attempt. The gatt handles are leaking.

This failure isn't reported any further, the connection attempt simply times out. A restart of the BLE stack "fixes" the issue – until 32 attempts are collected again.

A fix is to `.Close()` every gatt for every `.Disconnect()`. I'll provide a PR with a fix.

Seems similar to the symptoms in #481.

## Steps to reproduce

1. Attempt to connect to a known device in a loop. The device should not be nearby, so that the attempt times out
2. Attempt this at least 32 times. Observe `can't Register GATT client, MAX client reached: 32` in LOGCAT
3. Bring the device in a state where a connection attempt should be possible (power on, nearby, …)

## Expected behavior

A connection should be established.

## Actual behavior

No connection is established until one restarts the app or the devices BLE stack.

## Configuration

**Version of the Plugin: 2.1.1

**Platform:** Android 10

**Device:** Google Pixel

**Comment by smsissuechecker** [comment]
Hi @MKuckert,

I'm the friendly issue checker.
It seems like (25.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!
