### ISSUE TITLE
Cannot scan devices

### ISSUE THREAD

**Issue by yshteinm** [xabre/xamarin-bluetooth-le#488]
To help us fix your issue, please provide the information in the below template. If something causes a crash, provide as much information as you can gather.
Just imagine: we do not know what you are doing! 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.

## Steps to reproduce

1. Create Xamarin Forms app

2. Add Vanilla Nuget package

3. Implement start scan

## Expected behavior
Expect to get DiscoveredDevices events

## Actual behavior
No DiscoveredDevices events get called on Android 11

### Crashlog

If something causes an exception paste full stack trace + Exception here

## Configuration

**Version of the Plugin:**  2.1.1

**Platform:** Android 8 works, Android 11 doesn't

**Device:** Pixel

**Comment by smsissuechecker** [comment]
Hi @yshteinm,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by yshteinm** [comment]
Seems like duplicate of #480

**Comment by yshteinm** [comment]
Issue solved. If I may I would suggest to add this to your MD file. Starting Android 11 (not sure about 10) it is not enough to request permission for COARSE location permission. You need to ask for FINE location permission.
