### ISSUE TITLE
Automatically build nuget package

### ISSUE THREAD

**Issue by janusw** [xabre/xamarin-bluetooth-le#501]
As suggested in #445, it would be useful to have automatically-built nuget packages (as artifact of a CI build), for each commit on master and each PR at least. This could be done via Bitrise or GitHub Actions, for example.

**Comment by smsissuechecker** [comment]
Hi @janusw,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by janusw** [comment]
I discussed this with Adrian, and we agreed that GitHub Actions might be a reasonable replacement for the current Bitrise builds. I'll try to look into that soon.

**Comment by janusw** [comment]
The GitHub Actions config has been added with 22bed21. The first build (with logs) can be seen here:
https://github.com/xabre/xamarin-bluetooth-le/runs/2327558406
The corresponding artifacts (nuget packages) are here:
https://github.com/xabre/xamarin-bluetooth-le/suites/2478813162/artifacts/53361185
