### ISSUE TITLE
Scan unsuccessful until another app scanned.

### ISSUE THREAD

**Issue by 5CoJL** [xabre/xamarin-bluetooth-le#504]
EDIT:
I have noticed issues similar to mine have been submitted, and often result in a redirection to a closed issue. Since the recurring fix to these issues is often related to permissions, I want to specify this is not a permissions problem. The scan works perfectly fine for most devices I have handled, ranging from Android 8 to 11, with notably S10, S20. As for iOS, I have had no problem on any version/phones (iPhone 8/11/12).

Hello, I have had a strange error which I just can't figure out. I have an app using Plugin.BLE, and at some point I start a scan to detect a specific device type. After implementing the scan, it worked well (i.e it scanned and found the devices) on just about every phone I could lay my hands on, both Android and iOS. However, there is this one phone (Samsung Galaxy S10, Android v11.2) who would never find any device from the scanning operation. It seemed to be, by all evidence, a problem with this particular phone. However !

## Steps to reproduce

1. Scan for a bluetooth device using Plugin.BLE. The device is not found, no matter the amount of retries.

2. Scan for the same bluetooth device using the app nRF Connect. The device is found.

3. Scan for a bluetooth device using Plugin.BLE. The device is NOW found.

## Expected behavior
The initial scan should find the device without using another app.

## Actual behavior
The scan will not detect my device until another app discovered it prior.

## Configuration

**Version of the Plugin:** 2.1.1

**Platform:** Android 11

**Device:** Samsung Galaxy S10

**Comment by smsissuechecker** [comment]
Hi @5CoJL,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by 5CoJL** [comment]
Update: 
I have now fallen on another problem in the likes of the one detailled above.

On a Xiaomi XI9, I cannot find any devices when scanning with either my app using Plugin.BLE, or the app nRF Connect.
However, I find the devices via the Bluetooth App native to the phone. I cannot figure out if this is a problem from my app, Android or even the plugin.

**Comment by 5CoJL** [comment]
Ok, the issue was enabling the service location. I am _slightly_ ashamed.
