### ISSUE TITLE
error with nuget 

### ISSUE THREAD

**Issue by sebastienjouhans** [xabre/xamarin-bluetooth-le#52]
I tried to install the nuget package via the package manager but when I am trying to do so I get the following error

Install failed. Rolling back...
Package 'Plugin.BLE.1.0.0-beta4' does not exist in project 'BluetoothToggleWidget'
Package 'Plugin.BLE.1.0.0-beta4' does not exist in folder 'C:\Users\sebastienj\Documents\WORK\MyStuff\XamarinBLETest\Xamarin\AndroidChat\packages'
Install-Package : Failed to add reference to 'Plugin.BLE.Abstractions'.
At line:1 char:1
+ Install-Package Plugin.BLE -Pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 

Can you please fix it?

**Comment by smstuebe** [comment]
> Attempting to gather dependency information for package 'Plugin.BLE.1.0.0-beta4' with respect to project 'App1', targeting 'MonoAndroid,Version=v6.0.99'
Attempting to resolve dependencies for package 'Plugin.BLE.1.0.0-beta4' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Plugin.BLE.1.0.0-beta4'
Resolved actions to install package 'Plugin.BLE.1.0.0-beta4'
  GET https://www.nuget.org/api/v2/package/Plugin.BLE/1.0.0-beta4
  OK https://www.nuget.org/api/v2/package/Plugin.BLE/1.0.0-beta4 1276ms
Installing Plugin.BLE 1.0.0-beta4.
Adding package 'Plugin.BLE.1.0.0-beta4' to folder 'C:\Projekte\Temp\App1\packages'
Added package 'Plugin.BLE.1.0.0-beta4' to folder 'C:\Projekte\Temp\App1\packages'
Added package 'Plugin.BLE.1.0.0-beta4' to 'packages.config'
Successfully installed 'Plugin.BLE 1.0.0-beta4' to App1


It's working here. So you have to provide some more information. :)

**Comment by xabre** [comment]
@sebastienjouhans What's the status of this issue? Is it still occuring for you?

**Comment by xabre** [comment]
I'm guessing this has been solved. Will close.
