### ISSUE TITLE
Notification from two devices of the same type

### ISSUE THREAD

**Issue by vijaylzindia** [xabre/xamarin-bluetooth-le#520]
Is it possible to register for , and receive notification on the same characteristic from two devices of the same type which are connected to the phone? 

## Steps to reproduce

1. Connect to two devices of the same type (having same services and characteristics, same UUIDs).

2. Register for notification on a characteristic, for both devices. I have tried this by accessing the appropriate characteristic from the service for each device and then using await characteristic.StartUpdatesAsync();
              

## Expected behavior
Notifications from both devices should come in to the app

## Actual behavior
Only one of the notifications shows up

## Configuration

**Version of the Plugin:** 
2.1.2

**Platform:** 
Android 8.1

**Device:** 
Oppo

**Comment by smsissuechecker** [comment]
Hi @vijaylzindia,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.
