### ISSUE TITLE
Scan keeps bringing results from previous scans

### ISSUE THREAD

**Issue by CarlosVazAlves** [xabre/xamarin-bluetooth-le#521]
## Steps to reproduce

1. Scan for devices

2. Repeat scan

## Expected behavior
If there are 2 devices within range, only 2 devices should appear as the result of a scan, no matter ao many times you repeat the scan.

## Actual behavior
If there are 2 devices within range, first scan returns 2 devices. Second scan returns 4 devices, etc...

### Crashlog

No crash

## Configuration

**Version of the Plugin:** 2.1.2

**Platform:** Android 10 /  i0S 14 (Not sure about iOS version, I'm not using it)

**Device:** Galaxy S9 (Also tried with an AVD emulated device)

**Comment by smsissuechecker** [comment]
Hi @CarlosVazAlves,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by CarlosVazAlves** [comment]
Please ignore this issue.
Turns out, it was a bug in my code.
I apologize for the situation.
