### ISSUE TITLE
Is there a way to receive advertisement records from a BLE device and connect to it?

### ISSUE THREAD

**Issue by YomogiHerb** [xabre/xamarin-bluetooth-le#532]
To help us fix your issue, please provide the information in the below template. If something causes a crash, provide as much information as you can gather.
Just imagine: we do not know what you are doing! 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.

## Steps to reproduce

1. call adapter.StartScanningForDevicesAsync()

2. In adapter.DeviceDiscovered, extract advertisement records from the "device" , call adapter.StopScanningForDevicesAsync(), call ConnectToKnownDeviceAsync() with a cancel token to connect to the BLE device, then call adapter.DisconnectDeviceAsync()

3.

## Expected behavior
Tell us what should happen

## Actual behavior
DisconnectDeviceAsync sometimes doesn't reach the BLE device and the BLE device keeps connection state.

### Crashlog

If something causes an exception paste full stack trace + Exception here

## Configuration

**Version of the Plugin:** 2.1.2

**Platform:** Android 7

**Device:** Arrows M04

**Comment by smsissuechecker** [comment]
Hi @YomogiHerb,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by YomogiHerb** [comment]
It seems related to #215
