### ISSUE TITLE
VS2019 debug symbol for Plugin.BLE.dll is not valid.

### ISSUE THREAD

**Issue by byange** [xabre/xamarin-bluetooth-le#537]
## Steps to reproduce

1. Create Mobile App in VS2019 with TargetFramework "netstandard2.0" and  include "Plugin.BLE 2.1.2", "sqlite-net-pcl 1.8.116", "Xamarin.Forms 5.0.0.2083", "Xamarin.Essentials 1.7.0".

2. Using Plugin.BLE in LoginPage.xaml.cs and await Shell.Current.GoToAsync("//LoginPage") at App.xaml.cs OnStart.

3. Work at Android but failed at iOs as Crashlog.

## Expected behavior
Login page show.

## Actual behavior
Can't navigate to the login page.

### Crashlog

Debugging symbol file for '/Users/user/Library/Caches/Xamarin/mtbs/builds/xSph.iOS/668cca984114b8dd13abffaf6c8c1a99b362154d680918eb7b9d0df27d0dc38c/bin/iPhoneSimulator/Debug/Plugin.BLE.dll' is not valid and was ignored.

## Configuration

**Version of the Plugin: 2.1.2**

**Platform: Android 9.0 - API 28 / iOS 14.5**

**Device: Pixel 2.0 Pie 9.0 / iPhone 12**

**Comment by smsissuechecker** [comment]
Hi @byange,

I'm the friendly issue checker.
It seems like (37.50 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!
