### ISSUE TITLE
iOS: Pairing Process not working

### ISSUE THREAD

**Issue by HCLThiruG** [xabre/xamarin-bluetooth-le#538]
We have try to pairing devices(not for normal connect) for both iOS and Android. It is working well in Android but not working as expected in iOS. we unable to get Pairing dialog in iOS but it is connected. Please help us how to resolve this pairing problem in iOS.

**Comment by smsissuechecker** [comment]
Hi @HCLThiruG,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by HCLThiruG** [comment]
It is working when I do the write characteristic .
