### ISSUE TITLE
Xamarin.Mac support

### ISSUE THREAD

**Issue by hansmbakker** [xabre/xamarin-bluetooth-le#54]
Interesting project! Are there any plans to support the macOS platform?

I suspect that it should be quite similar to the iOS platform?

**Comment by smstuebe** [comment]
Not yet, but nice idea. We are currently focusing on the 1.0 stable release. And have some feature ideas for later releases.

**Comment by xabre** [comment]
ToDo:

- [ ] Create a functioning Xamarin.Mac collection view, with bindable item templates etc (or fix the current collection view which shows all items stacked on top of each other)
- [ ] Use this collection view for ServiceList, CharcateristicList and DescriptorList
- [ ] Finalize, unify Xamarin.Mac implementation of IUserDialogs
- [ ] Test all BLE functionality
- [ ] If appropriate, move the xamarin.mac and ios BLE implementation to a shared project and reference it from the platform implementations.

**Comment by smstuebe** [comment]
Hmm can we use a shared project or file linking please? Or are there too many differences? At the fingerprint plugin I've done it, too.

**Comment by flyingxu** [comment]
I hope it's not too late to suggest use Xamarin.Forms for Mac UI (https://blog.xamarin.com/preview-bringing-macos-to-xamarin-forms/). In that way, UI part will not be an issue and at least 3 more todo items in xabre's list might be marked as done.

**Comment by xabre** [comment]
2.1.0-pre1
