### ISSUE TITLE
it doesn't work with android 9 and 10

### ISSUE THREAD

**Issue by andrettaadriano1** [xabre/xamarin-bluetooth-le#540]
Hi, I have developed an android only application with your library and it works perfectly with android 6 and 7, but on two devices with android 9 and 10 it does not work (does not detect any devices).
do i need to request additional permissions? 
Thanks

**Comment by smsissuechecker** [comment]
Hi @andrettaadriano1,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by Karmageddonium** [comment]
Same thing on Android 10 using sample in the project

**Comment by LeeRising** [comment]
<uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
Add this permission into manifest, and it must working

**Comment by Karmageddonium** [comment]
> Add this permission into manifest, and it must working
"android.permission.ACCESS_BACKGROUND_LOCATION"

Also check if android settings location service is enabled (just in android settings as standart smartphone settings) or enable it in your code.
It appeared that it is not enough to request permission to location, it needs to be enabled as service in android.

**Comment by ohgils** [comment]
> > Add this permission into manifest, and it must working
> > "android.permission.ACCESS_BACKGROUND_LOCATION"
> 
> Also check if android settings location service is enabled (just in android settings as standart smartphone settings) or enable it in your code. It appeared that it is not enough to request permission to location, it needs to be enabled as service in android.
> 
> Finally it worked for me

I have same problem. please give me information how to fix it.
ble.isOn is true, ble.State is BluetoothState.On, adapter.IsScanning is true.
but can't found devices. (iOS can found with same sourcecode)

This is my AndroidManifest.xml permisstions.
<uses-sdk android:minSdkVersion="18" android:targetSdkVersion="29" />
<application android:label="TDX_XG.Android" android:theme="@style/MainTheme"></application>
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
<uses-permission android:name="android.permission.BLUETOOTH" />
<uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
<uses-permission android:name="android.permission.INTERNET" />
<uses-feature android:name="android.hardware.bluetooth_le" android:required="true" />

**Comment by ohgils** [comment]
I have same problem. please give me information how to fix it.
ble.isOn is true, ble.State is BluetoothState.On, adapter.IsScanning is true.
but can't found devices. (iOS can found with same sourcecode)

This is my AndroidManifest.xml permisstions.
```
<uses-sdk android:minSdkVersion="18" android:targetSdkVersion="29" />
<application android:label="TDX_XG.Android" android:theme="@style/MainTheme"></application>
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
<uses-permission android:name="android.permission.BLUETOOTH" />
<uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
<uses-permission android:name="android.permission.INTERNET" />
<uses-feature android:name="android.hardware.bluetooth_le" android:required="true" />
```

**Comment by ohgils** [comment]
> I have same problem. please give me some information how to fix it. ble.isOn is true, ble.State is BluetoothState.On, adapter.IsScanning is true. but can't found devices. (iOS can found with same sourcecode)
> 
> This is my AndroidManifest.xml permisstions.
> 
> ```
> <uses-sdk android:minSdkVersion="18" android:targetSdkVersion="29" />
> <application android:label="TDX_XG.Android" android:theme="@style/MainTheme"></application>
> <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
> <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
> <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
> <uses-permission android:name="android.permission.BLUETOOTH" />
> <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
> <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
> <uses-permission android:name="android.permission.INTERNET" />
> <uses-feature android:name="android.hardware.bluetooth_le" android:required="true" />
> ```

I found Samples BLE.Client.Droid. and it's no problem.
Thanks.

**Comment by janusw** [comment]
> Add this permission into manifest, and it must working "android.permission.ACCESS_BACKGROUND_LOCATION"

Note that in the normal case ACCESS_FINE_LOCATION should be sufficient. ACCESS_BACKGROUND_LOCATION should only be required if you want to scan in a background service (on Android 10 and above), see https://developer.android.com/guide/topics/connectivity/bluetooth/permissions#discover-local-devices.

**Comment by janusw** [comment]
> Could anyone please explain why we need the location at all to scan for Bluetooth devices?

From https://developer.android.com/guide/topics/connectivity/bluetooth/permissions#declare-android11-or-lower:

`ACCESS_FINE_LOCATION is necessary because, on Android 11 and lower, a Bluetooth scan could potentially be used to gather information about the location of the user.`

> And how to avoid using location completely..

Target Android 12. There you can use Bluetooth without the location permission, see https://developer.android.com/guide/topics/connectivity/bluetooth/permissions#assert-never-for-location.
