### ISSUE TITLE
Device Disconnected while writing characteristic

### ISSUE THREAD

**Issue by Amd3202** [xabre/xamarin-bluetooth-le#561]
To help us fix your issue, please provide the information in the below template. If something causes a crash, provide as much information as you can gather.
Just imagine: we do not know what you are doing! 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.
https://github.com/Amd3202/AstromechControlMvvm

## Steps to reproduce

1. Launch App, Click hamburger icon, Choose Device List, Click scan, Connect to BLE device

2.  on successful connection joystick control page should load

3. move the 2 joysticks around; ble will crash

## Expected behavior
Tell us what should happen
>>the app sends data to BLE device in string format; the data sends for a brief period (few seconds) then internally BLE discnnects even though the device light is still red. 

## Actual behavior
Tell us what happens instead
>>Should continue to send. 

### Crashlog
Device c015c32f-bf92-142b-6c14-dc02d4dd8ddc disconnected while writing characteristic with 0000ffe1-0000-1000-8000-00805f9b34fb.

If something causes an exception paste full stack trace + Exception here
  at Plugin.BLE.Abstractions.Utils.TaskBuilder.FromEvent[TReturn,TEventHandler,TRejectHandler] (System.Action execute, System.Func`3[T1,T2,TResult] getCompleteHandler, System.Action`1[T] subscribeComplete, System.Action`1[T] unsubscribeComplete, System.Func`2[T,TResult] getRejectHandler, System.Action`1[T] subscribeReject, System.Action`1[T] unsubscribeReject, System.Threading.CancellationToken token) [0x0011a] in <12956cfcb4ff491aa0cc1f7ab64b7e72>:0 
  at Plugin.BLE.Abstractions.CharacteristicBase.WriteAsync (System.Byte[] data, System.Threading.CancellationToken cancellationToken) [0x000a8] in <12956cfcb4ff491aa0cc1f7ab64b7e72>:0 
  at AstromechControl.Core.CustomControls.JoystickControl.SendBluetoothAsync () [0x001da] in D:\working_directory\AstromechContorlMvvm\AstromechControlMvvm\src\AstromechControl.Core\CustomControls\JoystickControl.cs:119 

## Configuration

**Version of the Plugin:** e.g. 1.0.0 / 1.0.1-alpha3
2.1.2 and 2.1.1 (tried both)

**Platform:** e.g. iOS 10.1 / Android 4.4 / ... (including version!!! e.g. Android 5.1 / i0S 10)
iOS -> 15.2.1 (happened last year too on iPhone X)

**Device:** e.g. HTC Sensation /i Phone 7 ...
Iphone 13 Pro (replicated on iPhone X)

**Comment by smsissuechecker** [comment]
Hi @Amd3202,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by Amd3202** [comment]
If this helps anyone here. Turns out somehow a blank row was being sent to the BLE. How exactly this was happening is unclear. I have not been able to reproduce it. But adding several empty-string checks seems to have solved it.

If this helps anyone:
` if (IsNullOrWhiteSpace(qItemAsString))
                            {
                                Debug.Write("!!!!QITEM AS STRING IS NULL!!!!!");
                                _ble.SetToAvailable();
                                continue;
                            }

                            // ReSharper disable once AsyncVoidLambda
                            Device.BeginInvokeOnMainThread(async () =>
                            {
                                Debug.Write($"About to write: {qItemAsString}");
                                var resp = await _char.WriteAsync(encodedBytes);
                                
                                //if (!resp)
                                //{
                                //    int i = 0;
                                //    //what is wrong?
                                //}

                                _lastX = Math.Abs(qItem.XPosition);
                                _lastY = Math.Abs(qItem.YPosition);
                            });`

**Comment by Amd3202** [comment]
would appreciate any feedback/ideas, seems to work fine for several seconds. but once lots of lines are sent (each line looks like this: 
H:74,80,35
H:86,66,48
(terminated with \n)

it crashes. 

```
  private async Task SendBluetoothAsync()
        {
            var anyBt = _ble.InputQueue().Any();

            if (!anyBt) return;

            while (anyBt)
            {
                try
                {
                    if (_ble.IsBusy())
                    {
                        await Task.Delay(1);
                        continue;
                    }

                    _ble.SetToBusy();
                    if (!_ble.InputQueue().Any())
                    {
                        _ble.SetToAvailable();
                        return;
                    }

                    AstromechInstructions qItem = _ble.InputQueue().Dequeue();
                    anyBt = _ble.InputQueue().Any();

                    if (qItem == null)
                    {
                        _ble.SetToAvailable();
                        continue;
                    }

                    // ReSharper disable once RemoveRedundantBraces
                    if (MovedEnough(qItem))
                    {
                        try
                        {
                            var qItemAsString = _ble.GetFormattedBleString(qItem);
                            Debug.Write(qItemAsString);

                            if (IsNullOrWhiteSpace(qItemAsString))
                            {
                                Debug.Write("!!!!QITEM AS STRING IS NULL!!!!!");
                                _ble.SetToAvailable();
                                continue;
                            }

                            var encodedBytes = Encoding.ASCII.GetBytes(qItemAsString);
                            
                            if(encodedBytes.Length ==0) continue;

                          
                                Debug.Write($"About to write: {qItemAsString}");
                                try
                                {
                                    var resp = await _char.WriteAsync(encodedBytes);
                                    if (resp == false)
                                    {
                                        Debug.Write("RESPONSE WAS FALSE ON WRITE!!!");
                                    }

                                    _lastX = Math.Abs(qItem.XPosition);
                                    _lastY = Math.Abs(qItem.YPosition);
                                }
                                catch (Exception ex)
                                {
                                    Debug.Write($"Exception on main thread! {ex.Message}");
                                }
                         
                        }
                        catch(Exception ex)
                        {
                            _lastX = 0;
                            _lastY = 0;
                            Debug.Write(ex.Message);
                        }
                    }

                    _ble.SetToAvailable();
                }
                catch (Exception ex)
                {
                    Debug.Write(ex.Message);
                    _ble.SetToAvailable();
                }
            }
           
        }```

**Comment by Amd3202** [comment]
OK! This seems to be a "rate" issue. Adding await Task.Delay(250); immediately before the write seems to have solved the issue. Hopefully this will help someone. It's not a bug in the code, though maybe something could be done to prevent this in the library?
