### ISSUE TITLE
I'll never scan out any Bluetooth.

### ISSUE THREAD

**Issue by bbhxwl** [xabre/xamarin-bluetooth-le#566]
I'll never scan out any Bluetooth.

code
```
 private async   void Button_Clicked(object sender, EventArgs e)
        {

            var ble = CrossBluetoothLE.Current;
            var rs = ble.State;
            var adapter = CrossBluetoothLE.Current.Adapter;
            adapter.ScanTimeout = 10000;
            adapter.DeviceDiscovered += Adapter_DeviceDiscovered;
           await adapter.StartScanningForDevicesAsync();
            Console.WriteLine();
            
        }
```

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="1" android:versionName="1.0" package="com.companyname.app3">
    <uses-sdk android:minSdkVersion="21" android:targetSdkVersion="30" />
    <application android:label="App3.Android" android:theme="@style/MainTheme"></application>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
  <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
  <uses-permission android:name="android.permission.BLUETOOTH_PRIVILEGED" />
  <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
  <uses-permission android:name="android.permission.BLUETOOTH" />
  <uses-feature android:name="android.hardware.bluetooth_le" android:required="true" />

</manifest>

```

**Comment by smsissuechecker** [comment]
Hi @bbhxwl,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by bbhxwl** [comment]
Resolved pending breakpoint at 'D:\Project\App3\App3\App3\MainPage.xaml.cs:84,1' to void App3.MainPage.Adapter_DeviceDiscovered (object sender, Plugin.BLE.Abstractions.EventArgs.DeviceEventArgs e) [0x0000e].

**Comment by janusw** [comment]
You're not telling use precisely enough what you're doing, how we can reproduce it or in which configuration you're building your stuff, and quite frankly ...

> I'll never scan out any Bluetooth.

... my English language parser just fails here with a semantics exception. I could try to guess what you mean (and what you're doing), but I don't have the time for that. Please open a proper bug report, and you will get proper help.

**Comment by bbhxwl** [comment]
> You're not telling use precisely enough what you're doing, how we can reproduce it or in which configuration you're building your stuff, and quite frankly ...
> 
> > I'll never scan out any Bluetooth.
> 
> ... my English language parser just fails here with a semantics exception. I could try to guess what you mean (and what you're doing), but I don't have the time for that. Please open a proper bug report, and you will get proper help.

At present, I can't search for ble devices in Android and IOS. I don't know why. I've only succeeded in windows.
