### ISSUE TITLE
BLE.Client.Droid does not properly request permissions at runtime

### ISSUE THREAD

**Issue by janusw** [xabre/xamarin-bluetooth-le#573]
## Steps to reproduce

1. Build BLE.Client.Droid.

2. Run it.

3. Scan.

## Expected behavior

Discovered devices should be listed.

## Actual behavior

Permission denied. Not scanning.

(After manually enabling the permissions in the app settings, it actually works. But the permissions should be actively requested by the app.)

### Crashlog

None.

## Configuration

**Version of the Plugin:** 2.1.2

**Platform:** Android 12

**Device:** Samsung Galaxy S21+

**Comment by smsissuechecker** [comment]
Hi @janusw,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by janusw** [comment]
In version 2.1.1 this still worked. Tapping the scan button triggers a request for the location permission.

**Comment by janusw** [comment]
It seems that this was broken (by myself) in #506.

**Comment by janusw** [comment]
Fixed via #574.
