### ISSUE TITLE
Error on iOS after ConnectToDeviceAsync()

### ISSUE THREAD

**Issue by jerkohren** [xabre/xamarin-bluetooth-le#586]
Hallo, my implementation of the library on Android works as expected. However, after I transfer to iOS, I have expirienced following problem:
Apr 14 11:26:44 reefmasterpi nymea-networkmanager[1035]:  I | NetworkManagerBluetoothServer: Controller state advertising...
Apr 14 11:26:44 reefmasterpi nymea-networkmanager[1035]:  I | NetworkManagerBluetoothServer: Set running true
Apr 14 11:26:44 reefmasterpi nymea-networkmanager[1035]:  I | NetworkManagerBluetoothServer: Bluetooth host in discoverable mode.
Apr 14 11:26:44 reefmasterpi nymea-networkmanager[1035]:  I | Application: Bluetooth server started
Apr 14 11:28:33 reefmasterpi nymea-networkmanager[1035]:  I | NetworkManagerBluetoothServer: Device connected "59:FB:58:90:45:CB"
Apr 14 11:28:34 reefmasterpi nymea-networkmanager[1035]:  I | NetworkManagerBluetoothServer: Controller state connected. "59-FB-58-90-45-CB" "59:FB:58:90:45:CB"
Apr 14 11:28:34 reefmasterpi nymea-networkmanager[1035]:  I | NetworkManagerBluetoothServer: Set connected true
Apr 14 11:28:34 reefmasterpi nymea-networkmanager[1035]:  I | NetworkManagerBluetoothServer: Client connected "59-FB-58-90-45-CB" "59:FB:58:90:45:CB"
Apr 14 11:28:34 reefmasterpi nymea-networkmanager[1035]:  I | Application: Bluetooth client connected
Apr 14 11:28:34 reefmasterpi nymea-networkmanager[1035]:  **W | qt.bluetooth.bluez: sending error response; request: 16 handle: 51 code: 10**

After this the App doesn't receive any WiFi list and it doesn't do anything. Do you have some idea what could be wrong?

**Comment by smsissuechecker** [comment]
Hi @jerkohren,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!
