### ISSUE TITLE
Bluetooth Classic

### ISSUE THREAD

**Issue by bojankostic81** [xabre/xamarin-bluetooth-le#603]
Hi, can we use this plugin to scan Bluetooth Classic devices as well?

**Comment by smsissuechecker** [comment]
Hi @bojankostic81,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!
