### ISSUE TITLE
Bluetooth Classic

### ISSUE THREAD

**Issue by bojankostic81** [xabre/xamarin-bluetooth-le#604]
Hi, can we use this plugin to scan Bluetooth Classic devices as well?

## Steps to reproduce

1. Add BLE plugin to Xamarin Forms app

2. Scan for Bluetooth devices

## Expected behavior
Display all BT devices, including classic BT devices

## Actual behavior
Some of devices were not displayed in the list. However they are displayed on the phone Bluetooth list

### Crashlog

If something causes an exception paste full stack trace + Exception here

## Configuration

**Version of the Plugin:** e.g. 1.0.0 / 1.0.1-alpha3

**Platform:** e.g. iOS 10.1 / Android 4.4 / ... (including version!!! e.g. Android 5.1 / i0S 10)

**Device:** e.g. HTC Sensation /i Phone 7 ...

**Comment by smsissuechecker** [comment]
Hi @bojankostic81,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by janusw** [comment]
> Hi, can we use this plugin to scan Bluetooth Classic devices as well?

No, this plugin only supports Bluetooth Low Energy, not Bluetooth Classic.
