### ISSUE TITLE
Ble Device pairing

### ISSUE THREAD

**Issue by Karteeka18** [xabre/xamarin-bluetooth-le#624]
We have a new Ble Device we are using to connect to UWP, Android, and iOS devices. 
We have used the "Plugin. BLE" library for our other Ble Devices. https://github.com/xabre/xamarin-bluetooth-le.
This new Device requires Pairing for encryption to be effective. We have used ConnectAsync() methods but it only connects it does not Pair. Are there any methods we could use for Pairing a Ble?

**Comment by smsissuechecker** [comment]
Hi @Karteeka18,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!
