### ISSUE TITLE
Add support for MAUI build targets

### ISSUE THREAD

**Issue by milten89** [xabre/xamarin-bluetooth-le#632]
Please add support for MAUI build targets other than Android. 
I'm starting work on a new multiplatform application in MAUI that require Bluetooth LE. Right now, the only multiplatform library that I can find and support all MAUI build targets is _InTheHand.BluetoothLE_, but API is prehistorical and for production use it needs to be wrapped. _Plugin.BLE_ has much better API, and it's easier to use.
I don't know if current support for Android is intentional or because build target in Xamarin and MAUI for Android are the same. When I'm looking on iOS and UWP code, everything looks ok, and should work, but I'm just starting to work in MAUI (don't have any Xamarin experience) and maybe can't see some obvious problems with new build targets.

## Steps to reproduce

1. Add _Plugin.BLE_ to default MAUI project using NuGet.

2. Change debug target to _Windows Machine_ or _iOS device_

3. Try get _CrossBluetoothLE.Current_ object.

## Expected behavior
Return valid IBluetoothLE implementation depending on OS

## Actual behavior
Throw **System.NotImplementedException** with message: _This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation._

### Crashlog

```
System.NotImplementedException
  HResult=0x80004001
  Message=This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.
  Source=Plugin.BLE
  StackTrace:
   at Plugin.BLE.CrossBluetoothLE.get_Current()
   at maui_ble.MauiProgram.CreateMauiApp() in C:\git\maui_ble\MauiProgram.cs:line 24
   at maui_ble.WinUI.App.CreateMauiApp() in C:\git\maui_ble\Platforms\Windows\App.xaml.cs:line 22
   at Microsoft.Maui.MauiWinUIApplication.OnLaunched(LaunchActivatedEventArgs args)
   at ABI.Microsoft.UI.Xaml.IApplicationOverrides.Do_Abi_OnLaunched_0(IntPtr thisPtr, IntPtr args)
```

## Configuration

**Version of the Plugin:** 2.2.0-pre5

**Platform:** iOS - all versions, Windows - all versions

**Device:** all non-android devices

**Comment by smsissuechecker** [comment]
Hi @milten89,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by milten89** [comment]
YES :D This is exactly what I need. Thanks.
