### ISSUE TITLE
Can't build BLE.sln on Windows 10/Visual Studio 2015 Community Ed.

### ISSUE THREAD

**Issue by gaminn** [xabre/xamarin-bluetooth-le#68]
Hi,
it is impossible to build the solution on Windows 10/Visual Studio 2015 Community Edition/latest Xamarin. The error is:

Error		No resource found that matches the given name: attr 'colorAccent'.	BLE.Client.Droid	D:\Projects\Test\xamarin-bluetooth-le\Source\BLE.Client\BLE.Client.Droid\Resources\values\style.xml	2	
Error		No resource found that matches the given name: attr 'colorPrimaryDark'.	BLE.Client.Droid	D:\Projects\Test\xamarin-bluetooth-le\Source\BLE.Client\BLE.Client.Droid\Resources\values\style.xml	2	
Error		No resource found that matches the given name: attr 'windowActionModeOverlay'.	BLE.Client.Droid	D:\Projects\Test\xamarin-bluetooth-le\Source\BLE.Client\BLE.Client.Droid\Resources\values\style.xml	2	
Error		Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.NoActionBar'.	BLE.Client.Droid	D:\Projects\Test\xamarin-bluetooth-le\Source\BLE.Client\BLE.Client.Droid\Resources\values\style.xml	2	
Error		No resource found that matches the given name: attr 'colorPrimary'.	BLE.Client.Droid	D:\Projects\Test\xamarin-bluetooth-le\Source\BLE.Client\BLE.Client.Droid\Resources\values\style.xml	2

**Comment by smstuebe** [comment]
Have you updated your android SDK tools, the support library and the platform?

**Comment by gaminn** [comment]
I installed all last week from internet.

**Comment by smstuebe** [comment]
Have you double checked by opening the Android SDK manager?

**Comment by gaminn** [comment]
I have:
Android SDK Tools rev. 25.1.7
Android 7.0 (API 24) SDK Platform 24, rev. 2
I don't know what the support library is. I don't see it in Android SDK Manager.

**Comment by smstuebe** [comment]
AndroidUseLatestPlatformSdk is currently set to false and the compile sdk to 6.0
Can you try to install Android 6.0 (API 23) or change the "compile using android Version" setting to "7.0", "use latest", respectively in the project settings of the android project?

**Comment by gaminn** [comment]
I changed target SDK to several lower versions and it doesn't help.

**Comment by smstuebe** [comment]
Support library is in "Extras" group.

![image](https://cloud.githubusercontent.com/assets/7632775/17535622/07e26de0-5e90-11e6-9269-1970c57cd9c5.png)

a) Do you have this?
b) Have you updated some nuget packages of the sample project?

I can't really help you more :< The automated build on bitrise is running and it is compiling on our machines

**Comment by gaminn** [comment]
Yes, I have the latest Android Support Library. I haven't seen it as it was hidden under obsolete checkbox.

I tried to update all nuget packages, but during update I get the same errors a when building the solution.

OK, consider this issue unresolved.

**Comment by smstuebe** [comment]
@xabre do you have any idea?

**Comment by xabre** [comment]
I'll take a look. I'dont have API level 24 installed on my machines. Also check this: [https://releases.xamarin.com/technical-bulletin-android-sdk-build-tools-24/](https://releases.xamarin.com/technical-bulletin-android-sdk-build-tools-24/). 

@gaminn Just one quick question, if you create a new empty xamarin forms app in VS can you build the android app, just like that without any changes? 

Also make sure not to update the nuget packages in the solution for xamarin android support (even if vs usggests it). Xamarin forms has a fixed dependecy on i think (=23.3.0).

**Comment by gaminn** [comment]
Yes, no problem in creating blank Xamarin.Forms solution and then building it.

**Comment by xabre** [comment]
I've just installed API level 24 together with the latest sdk build tools (24.0.1). I had to update JDK to 1.8 (Java8) but after that everything builds smoothly. 

@gaminn My current suggestion is :

- clone a fresh copy (or git reset --hard and git clean -f -d- x) 
- checkout the 1.1.0 branch (we just updated all the nuget packages in this branch to the latest supported version)
- restore nuget pacakges (right clicok on solutin -> Restore)
- check that the Xam.AndroidSupport.V7 library (see screenshot1) is installed correctly
- check that xamarin correctly downloaded the Android Java repository for the support lib (see screenshot 2). 
- rebuild

The errors you are experiencing is most likely cause by something related to this specific support library Theme.AppCompat.* come from here.

**Screen1: VS** 
![issue](https://cloud.githubusercontent.com/assets/6204446/17571423/69cb82e2-5f50-11e6-8518-86e0b9476fce.png)

**Screen2: Xamarin AppData**
![issue](https://cloud.githubusercontent.com/assets/6204446/17571738/bb862e06-5f51-11e6-8e30-bacaad5d9567.png)

**Comment by xabre** [comment]
@gaminn any news in this one?

**Comment by gaminn** [comment]
> check that xamarin correctly downloaded the Android Java repository for the support lib (see screenshot 2). 

My AppData\Local\Xamarin\Xamarin.Android.Support.v7.AppCompat\23.3.0.0 folder is empty. How to fix it?

**Comment by smstuebe** [comment]
Delete and rebuild

**Comment by xabre** [comment]
`git clean -f -d- x`
also delete the empty folders in AppData

**Comment by gaminn** [comment]
I downloaded android_m2repository_r29.zip (as Visual Studio instructed me to download it and extract it in 23.3.0.0 folder) and extracted in AppData\Local\Xamarin\Xamarin.Android.Support.v7.AppCompat.

Still the same errors.

I would like to thank you for your support but it seems we are not able to resolve this issue. Please close it, I'm not longer interested in buiding the solution.
