### ISSUE TITLE
Plain Vanila Plugin crash when scanning with GUID.

### ISSUE THREAD

**Issue by alberk8** [xabre/xamarin-bluetooth-le#69]
## Steps to reproduce

1.
//This statement crash if I have the GUID, without any parameter it works but it would return 
//every BLE device in the vicinity.
_bleAdapter.StartScanningForDevicesAsync(new[] { Guid.Parse("ffe0ecd2-3d16-4f8d-90de-e89e7fc396a5") });
2.

3.

## Expected behavior
The Plugin Should be able to scan for the specific device by GUID

## Actual behavior
The App Crash

### Crashlog
![screenshot_1](https://cloud.githubusercontent.com/assets/12510130/17503494/d25721b0-5e22-11e6-9622-24aee18c9c20.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/12510130/17503496/d6b9c8ca-5e22-11e6-822c-706442df6cef.png)

## Configuration

**Version:**  
Plugin BLE 1.0.0 Release
Xamarin 4.1.2.18
Xamarin.Android 6.1.2.21
Visual Studio 1514.0.25421.03 Update 3

**Platform:** iOS/Android/ ...
Android 6.0.1 

**Device:** Xiaomi Redmi 3S..

**Comment by smstuebe** [comment]
In your crash log I see `ConnectToDeviceAsync` are you sure, that it happens on `StartScanningForDevicesAsync`? Do you have more code or a minimal example?

**Comment by alberk8** [comment]
Hi,

I did some more debugging on my code and it is true that the ConnectToDeviceAsync was called.  My mistake was not to have checked ` _adaptor.DiscoveredDevices.Count > 0` first.  When calling `ConnectToDeviceAsync( _device )` where the _device is null will cause the application to crash.

Is it possible to change the behavior of `ConnectToDeviceAsync`  to throw an Exception instead of blowing up?.

Thanks.

**Comment by smstuebe** [comment]
ye, we can throw an `ArgumentNullException` on here.
