### ISSUE TITLE
Enhancement: IsEnabled for Service and Characteristic

### ISSUE THREAD

**Issue by alberk8** [xabre/xamarin-bluetooth-le#77]
I would be good to have an additional `IsEnabled` property for `GetServiceAsync` and `GetCharacteristicAsync`.

Use Case:
I have a `System.Timers.Timer` loop in the background to query for data from BLE devices (more than one device type).  The issue is that not very BLE device are make equal,  Sometimes, when the `GetServiceAsync` and `GetCharacterisAsync` are called and returns without any exceptions but it is instance the service and characteristic is not wired up.  So if I call the `WriteAsync() `,  it will throw an exception.  I would be good if I can test the condition before calling.    

```
try{
_Service = await _Device.GetServiceAsync(Guid.Parse(ServiceGuid));
_Characteristic = await _Service.GetCharacteristicAsync(Guid.Parse(RWGuid));
_NotifyCharacteristic = await _Service.GetCharacteristicAsync(Guid.Parse(NotifyGuid));
await Task.Delay(150);
}
catch(Exception ex)
{
  Log.Info(TAG,"Error "+ex.Message);
}
//
try{
await _Characteristic.WriteAsync(cmd);
}
catch(Exception ex)
{
  Log.Info(TAG,"Error Writing"+ex.Message);
}


```

**Comment by smstuebe** [comment]
What should `IsEnabled` do?

**Comment by alberk8** [comment]
`IsEnabled ` should be a bool to indicate if the underlying service/characteristic is wired up and active.

**Comment by smstuebe** [comment]
What does this mean? Which properties/states indicate the states `wired up` and `active`?

**Comment by xabre** [comment]
I'm guessing this issue is kind of stale ...
