### ISSUE TITLE
Enable setting PeripheralScanningOptions for ScanForPeripherals on iOS

### ISSUE THREAD

**Issue by jasonchester** [xabre/xamarin-bluetooth-le#82]
## Enhancement Request - Enable setting PeripheralScanningOptions in IOS.

Certain BLE use cases where BLE Peripherals are operating in a Broadcast only mode require the ability to pass peripheral scanning options to the CBCentralManager.ScanForPeripherals() method.

*Plugin.BLE.iOS/Adapter.cs*@Line128

		protected override async Task StartScanningForDevicesNativeAsync(Guid[] serviceUuids, CancellationToken scanCancellationToken)
		{
			// Wait for the PoweredOn state
			await WaitForState(CBCentralManagerState.PoweredOn, scanCancellationToken).ConfigureAwait(false);

			Trace.Message("Adapter: Starting a scan for devices.");

			CBUUID[] serviceCbuuids = null;
			if (serviceUuids != null && serviceUuids.Any())
			{
				serviceCbuuids = serviceUuids.Select(u => CBUUID.FromString(u.ToString())).ToArray();
				Trace.Message("Adapter: Scanning for " + serviceCbuuids.First());
			}

			DiscoveredDevices.Clear();

			// Need ability to pass PeripheralScanningOption values to this method.
			_centralManager.ScanForPeripherals(serviceCbuuids, new PeripheralScanningOptions { AllowDuplicatesKey = true });
        }

Apple Documentation describes this use case...

> Turning off the default behavior can be useful for certain use cases, such as initiating a connection to a peripheral based on the peripheral’s proximity (using the peripheral received signal strength indicator (RSSI) value).

- https://developer.apple.com/library/ios/documentation/NetworkingInternetWeb/Conceptual/CoreBluetooth_concepts/BestPracticesForInteractingWithARemotePeripheralDevice/BestPracticesForInteractingWithARemotePeripheralDevice.html#//apple_ref/doc/uid/TP40013257-CH6-SW4

## Helpful Links
- https://developer.xamarin.com/api/type/CoreBluetooth.PeripheralScanningOptions/
- https://developer.xamarin.com/api/member/CoreBluetooth.CBCentralManager.ScanForPeripherals/p/CoreBluetooth.CBUUID[]/CoreBluetooth.PeripheralScanningOptions/
- http://stackoverflow.com/a/22837799
- http://stackoverflow.com/a/12486927

## Configuration
*Xamarin.Forms*
Vanilla *Plugin.BLE* (no MvvmCross)

**Version:** <1.1.0-beta1

**Platform:** iOS

**Device:** All iOS

**Comment by xabre** [comment]
Check out 1.1.0-beta4
