### ISSUE TITLE
Plugin.BLE API for iOS - retrieveConnectedPeripheralsWithServices & getConnectedDevices Android

### ISSUE THREAD

**Issue by leelatoo** [xabre/xamarin-bluetooth-le#86]
Hi,

In iOS, we have an API 'retrieveConnectedPeripheralsWithServices' to retrieve the peripherals which are currently connected to the system.

What is the equivalent API in Plugin.BLE?

Thanks

**Comment by xabre** [comment]
This method belongs to the iOS native api. Currently the plugin does not expose this method, before we can expose it we need to investigate what the equivalent Android implementation would look like and then create the abstraction. Pull requests are welcome :)

**Comment by leelatoo** [comment]
Thank you :)

**Comment by xabre** [comment]
1.1.0-beta5
