### ISSUE TITLE
Access BLE device object from characteristic updated event

### ISSUE THREAD

**Issue by leelatoo** [xabre/xamarin-bluetooth-le#90]
Hi,

We register for characteristic notifications using 
characteristic.ValueUpdated += (o, args) =>
{
    var bytes = args.Characteristic.Value;
}

Whenever characteristic value is updated, ValueUpdated event is fired.
form the event, we can access the characteristic and its value.

I want to access Parent BLE device object from this event. 
I noticed that Characteristic object has a private variable _parentDevice.

How do i get access to the parent device object from the characteristic updated event?

In iOS, whenever a characteristic value changes, "peripheral:didUpdateValueForCharacteristic:error: " gets called. Here, we can access the peripheral device.

**Comment by xabre** [comment]
So you need an exposed IDevice ParentDevice property in the characteristic? 

For the moment _parentDevice which is CBPeripherial is only used in the iOS internal implementation. On android the internal implementation does not need any reference to the BluetoothDevice so there was no reason to expose this property in the shared api at that time. We will consider this. 

Until then you can always store a reference to your Idevice instance > get service > get characteristic  > start updates > onvalue updated > use the stored idevice instance ... unless you have several connected devices which you all subscribe to the same event handler... Did I understand this correctly?

**Comment by leelatoo** [comment]
Yes, your understanding is correct.

I have multiple connected devices, subscribed for updates to the same event handler.
Now, there is a need to differentiate the characteristics updates. I want to know the which device's characteristic got updated?

**Comment by leelatoo** [comment]
If  different event handlers are used for different devices, i should be able to detect which device's characteristic got updated. right?

Is there any other better approach to identify device from Characteristic value updated event?

**Comment by leelatoo** [comment]
Hi,

We want to access native device object when a peripheral's characteristic value gets updated.

In iOS, "peripheral:didUpdateValueForCharacteristic:error: " gets called when a characteristic notifies. Here we get access to peripheral device object.

In Android, "onCharacteristicChanged (BluetoothGatt gatt, BluetoothGattCharacteristic characteristic)" gets called when a characteristic notifies. Here, we get access to BluetoothGatt object which in turn has BluetoothDevice object as mDevice.

Can you please provide a common API to access this native device object when a characteristics value gets updated?

**Comment by leelatoo** [comment]
Hi,

We are in need of the 'BLE device object access' for our project. 
When can we expect this functionality?

Or, Can you please provide us some suggestions to get access to the BLE device object when a notification is arrived?

**Comment by xabre** [comment]
@leelatoo I will take a look at his feature hopefully this week. I will publish a beta release as soon as it's ready.

**Comment by smstuebe** [comment]
@leelatoo But keep in mind: beta doesn't mean stable (API + Implementation)!

**Comment by leelatoo** [comment]
@xabre Thank you.

@smstuebe ok.

**Comment by xabre** [comment]
@leelatoo Just released 1.2.0-beta1. You can access the device using charactersitic.Service.Device. Let me know if you have any problems.

**Comment by leelatoo** [comment]
@xabre Hi,

We used Plugin.BLE 1.2.0-beta1 in our project. We are able to access device object when a notification arrives :)

Thanks a lot for the support 👍
