### ISSUE TITLE
Android 4.4 StartScanningForDevicesAsync() no results

### ISSUE THREAD

**Issue by andrew-nemtsev** [xabre/xamarin-bluetooth-le#96]
The following issue is observed for Vanilla Plugin.BLE:
DeviceDiscovered event is triggered for Android 5.x and 6.x, but not for Android 4.4

Example project
https://github.com/andrew-nemtsev/plugin_ble_android4_issue

## Steps to reproduce

1. Start app @ Android 4.4 device in range of any BLE-advertising device

2. Press the button

## Expected behavior
"DISCOVERED" toast is appeared

## Actual behavior
"DISCOVERED" toast is NOT appeared

## Configuration

**Version:** 1.0.0 and 1.1.0 beta-2

**Platform:** Android 4.4.2

**Device:** Fly Evo Tech 3 IQ4414 Quad

**Comment by xabre** [comment]
What doe LogCat say? Are there any errors/warnings in the output?
I have tested the lib with a Samsung Galaxy S3 Neo (4.4) and it works fine.

**Comment by smstuebe** [comment]
No response within 3 weeks -> closed :facepunch:
